### ISSUE TITLE
Lamp Causes Light Leak Through Hatches After Open & Close

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#12087] opened 2023-05-27 19:46 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The lamp, when you open and close a hatch with buttons, the light will keep shining through the hatch even when it's closed. Example: Room is somewhat lit, you open the hatch with buttons, now the room is brighter, close the hatch and the room stays lit

https://github.com/Regalis11/Barotrauma/assets/20964160/46a4eb3d-208b-42e7-8de8-c374e7ea4892

### Reproduction steps

Shown in video

![Screenshot 2023-05-27 122553](https://github.com/Regalis11/Barotrauma/assets/20964160/41d8a356-9a0c-4ed4-8eed-b713879561ee)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

[light issue.zip](https://github.com/Regalis11/Barotrauma/files/11582967/light.issue.zip)

**Comment by Regalis11** [comment] 2023-05-29 12:22
Thank you for the report!

I gave this a test, and it seems to be caused by how the lighting system marks convex hulls (things that cast shadows) as "hidden" from the light's point of view if they're behind a wall or an obstacle. The issue here is the door goes behind the floor structure when it's closing, marking it as "hidden", and the light will ignore it from that point onwards. Need to think a bit about a way to address this (forcing the door to become "unhidden" for all lights whenever it opens/closes wouldn't be ideal, because it'd significantly increase the amount of light calculations and be bad for performance).

**Comment by Regalis11** [comment] 2024-05-31 07:46
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/ade16256ada67b560899b7f26a639b002a37a401

**Comment by NilanthAnimosus** [comment] 2024-08-26 10:50
Closing as tested and merged for the next patch/unstable.

**Closed by NilanthAnimosus** 2024-08-26 10:50 UTC
Labels: Bug, Code
