### ISSUE TITLE
[Unstable] Clicking any item with light component imbedded in it but not being main one crashes you

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#13436] opened 2024-02-15 21:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clicking rapidly on objects like Light Tower, Surgical Lights, Street Light, Research Container, Research Table or Hologram Display will cause you to crash without logs.

### Reproduction steps

1. start sub editor
2. place items out of list (Clicking rapidly on objects like Light Tower, Surgical Lights, Street Light, Research Container, Research Table or Hologram Display will cause you to crash without logs.)
3. rapiddly click on em
4. ecounter crash

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.10.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment] 2024-02-15 21:59
What about crashreportslim.log?

**Comment by SeaDrinker** [comment] 2024-02-15 22:34
For me the game freezes for a split second when clicking on one of the objects before crashing to desktop. I've gotten a crash notice a few times but usually don't. I do get an update to my crashreports though.
[crashreportslim_cursedlightitems.txt](https://github.com/FakeFishGames/Barotrauma/files/14303027/crashreportslim_cursedlightitems.txt)

**Comment by Regalis11** [comment] 2024-02-16 07:12
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13378

**Closed by Regalis11** 2024-02-16 07:12 UTC
