### ISSUE TITLE
Stun baton without a battery cannot be used.

### ISSUE THREAD

**Issue by JohnBrick0** [FakeFishGames/Barotrauma#13427] opened 2024-02-13 19:05 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was fighting a group of small threshers, and I was hitting them with a stun baton. After the battery in the baton depleated i was unable to take normal swings with it and deal damage. I was only getting the red notification about a lack of battery, as if I were out of ammo while trying to shoot the gun. I asked my friends to try using the empty stun baton, and they also couldn't do that.

### Reproduction steps

1. Start a campaign 
2. Spawn a stun baton
3. Take out the battery out of the stun baton or depleate it
4. Try using a stun baton without power

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-02-14 07:13
Thank you for the report! Most likely caused by the same issue as https://github.com/FakeFishGames/Barotrauma/issues/13298, should be fixed in the latest unstable

**Comment by Regalis11** [comment] 2024-03-01 13:23
Seems to have been fixed, closing

**Closed by Regalis11** 2024-03-01 13:23 UTC
Labels: Bug, Needs testing, Code
