### ISSUE TITLE
people are leaving or staying in spectator after connection

### ISSUE THREAD

**Issue by DrBruhman** [FakeFishGames/Barotrauma#13438] opened 2024-02-16 20:43 UTC
why people are leaving or staying in spectator after connection? vanilla, respawn enabled, and working for some people, low(50-150) ping. my pub cant get population more than 4 with this phenomenon. no errors(mostly). unfun fact that most people that join and respawns correctly are ruiners.

**Comment by Regalis11** [comment] 2024-02-19 12:44
Thank you for the report!

I'm not entirely sure I understand the issue correctly. What do you mean by "leaving or staying in spectator" - that the players become spectators when a new round starts, or that they don't get to spawn even if they want to play as non-spectators? Do the clients randomly switch between those two, or does each client seem to get "locked" as either a spectator or non-spectator?

Are you using some kind of mods or non-default server settings?

**Comment by DrBruhman** [comment] 2024-02-21 06:27
me and my friend playing campaign on my vanilla server. sometimes randoms connect and join mid-round on shuttle but mostly they just stay in spectator mode from my perspective(tab menu), and stays in that state for couple minutes before leaving. probably its issue from their side, but it happens too often. or they just pressed spectator flag for some reason idk. next time this happens i should contact them and ask

**Comment by Regalis11** [comment] 2024-03-15 12:57
I believe I found the cause to this. Seems that the server interprets the response to the "do you wait for the next round to respawn" as "do you want to spectate". Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/5965a1a17bf87b5926a130f855afbabbcf08fe48 (commit in our private repo).

**Comment by Rokvach** [comment] 2024-05-29 03:05
Tested, working correctly. Closing.

**Closed by Rokvach** 2024-05-29 03:05 UTC
Labels: Bug, Networking
