### ISSUE TITLE
Custom characters holds items and swim under water with inverted arms (slugcat)

### ISSUE THREAD

**Issue by kleiner-sentry** [FakeFishGames/Barotrauma#13388] opened 2024-02-04 06:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm modding a custom character that's very similar anatomically to humans. The character itself is smaller than humans, and the arms are even smaller. Anytime I use it to pick up a tool and use it, or swim in the water, my hands are exactly inverted by 180 degrees However using the tools behaves normally. Inverting the joints solves this problem, but then the arms seem to snap into specific angles. I've verified my game multiple times, and have had me and another person try to fix it in the character file ourselves, to no avail. I've attached my character file so you can reproduce it.

[Slugcat.zip](https://github.com/FakeFishGames/Barotrauma/files/14155681/Slugcat.zip)

![20240203220443_1](https://github.com/FakeFishGames/Barotrauma/assets/5957082/36dc3495-9923-4ee8-93b4-c77a2fbbee2b)
![20240203220447_1](https://github.com/FakeFishGames/Barotrauma/assets/5957082/9ede34ea-796f-49c9-893c-c58a3c7c71d7)
![20240203220512_1](https://github.com/FakeFishGames/Barotrauma/assets/5957082/76167fa9-bcc9-4a66-8514-c21f95182543)
![20240203220538_1](https://github.com/FakeFishGames/Barotrauma/assets/5957082/cb5bc100-cdfa-4f98-97ce-76bb14ed6697)

### Reproduction steps

1. Spawn the custom character, and control it.
2. Hold an item, or swim under water.
3. Observe its arms.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-02-04 07:30
Thank you for the report!

On a cursory look at the xml, I would suspect that the issue is how the rotation limits of the shoulders (the joint between the torso and the arm) are configured. The vanilla humanoid characters have no rotation limits on the shoulders. If there are limits, it will prevent the arm from rotating past certain angles (probably what you mean by the arms snapping to specific angles). I would try removing the limit from the shoulder by disabling the "Limit enabled" setting. Please let us know if that doesn't help!

**Comment by kleiner-sentry** [comment] 2024-02-04 11:10
I've already done this on the character. I've also attempted to copy a lot of the rotational limits from the human model, and it doesn't seem to fix anything.

**Comment by Regalis11** [comment] 2024-02-14 15:21
Sorry for taking so long to get back to you!

I took a proper look at this now, and it seems that this can be fixed by inverting the "spritesheet orientation" setting in the editor (for some reason, it points in the opposite direction than the human spritesheet). Another issue was that the "Hand Clamp Y" value was set to 0.5 meters above the character's torso, that need to be inverted as well.

To be honest, I'm not even completely sure how the sprite sheet orientation is intended to work or why it needs to point downwards in this case. I think we need to take a closer look at this and make it's usage and purpose more clear. Which applies to a lot of things in the character editor - I'm impressed that you've even managed to figure it out well enough to build a completely custom humanoid character that works this well!

Here's a modified version of the character, with functional arms, in case you want to take a loot what exactly I changed:
[Slugcat.zip](https://github.com/FakeFishGames/Barotrauma/files/14281571/Slugcat.zip)

**Comment by itchyOwl** [comment] 2024-02-14 17:38
The sprite orientation indicates what's the up or forward direction of the sprite (= the zero point of the rotation). We use it for offsetting some calculations regarding whether the limb is pointing towards a target or not (e.g. a ranged weapon). Or, like here: what's the desired arm angle of the hand IK.

For limbs that are middle of the character, it might not be clear what that should be (and in most cases it might not even matter) but for the rest: it's the direction when they point **directly outwards from the main limb**. Note that there's a general **spritesheet orientation** for the entire spritesheet _and_ an override setting for each sprite. By default all the sprites use the general spritesheet orientation, unless you select a limb and then adjust the setting (now saying "Sprite Orientation" instead of Spritesheet Orientation").

![image](https://github.com/FakeFishGames/Barotrauma/assets/5370738/ef12f6dd-dc42-4054-bba3-d50ddd4b17ba)

![image](https://github.com/FakeFishGames/Barotrauma/assets/5370738/afebb657-d5b5-46cf-9394-8d55f4d8e1b5)

So, for example this is how the orientations have been defined for the human character:
![image](https://github.com/FakeFishGames/Barotrauma/assets/5370738/5f5d115e-e3a7-4dec-aa57-5706bce79491)

Normally you should make the sprites facing either up, down, left, or right, but if the sprites are not drawn like that, like on Crawler, we'd have to adjust the sprite orientation to match the orientation of the sprite, like so:
![image](https://github.com/FakeFishGames/Barotrauma/assets/5370738/799b729e-eb45-4bb4-8024-5d756c37d793)

**Comment by kleiner-sentry** [comment] 2024-02-15 02:59
Thank you guys so much!

**Closed** 2024-02-16 12:16 UTC
