### ISSUE TITLE
[UNSTABLE] Symbiosis gunners refuse to fire upon attacking husk crawlers

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#12836] opened 2023-10-18 21:44 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Symbiosis crew will refuse to fire upon husked crawlers from submarine guns but will gladly kill them if they board + they dont hesitate much on normal husks under same conditions

### Reproduction steps

1. use a save or commands in sub editor level to get husk symbiosis affliction on crewmemeber and put him on guns of submarine
2. spawn husked crawler
3. observe issue

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-23 10:05
Thank you for the report! I'm afraid I couldn't reproduce the issue:


https://github.com/Regalis11/Barotrauma/assets/14351070/886230ff-4bb1-481a-b4fb-22c52e677e41

**Comment by Regalis11** [comment] 2024-02-02 16:39
No known steps to repro, closing

**Closed by Regalis11** 2024-02-02 16:39 UTC
Labels: Bug, Need more info, Code
