### ISSUE TITLE
Microphone stops working during game

### ISSUE THREAD

**Issue by Arthuriada** [FakeFishGames/Barotrauma#3937] opened 2020-09-28 09:12 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When launch game and set mic it works fine, but after a minute of gameplay noone can hear me
If I set it off in game settings, and enable it again, it will work another minute

What has been done so far:
Different drivers tested
Microphone renamed to MyMic in registry
Exclusive mode ticked/unticked
Power options checked
PC tested for malware and software conflicts. No other applications/services that might use mic was detected at the moment of testing
Wires and different headset has been tested

**Steps To Reproduce**
N/A

**Version**
Windows 10
Ver 0.10.5.1

**Additional information**
Other applications work fine with no mic issues. Override solution is Discord, but it cuts me off most of players community. Communication is the essense of coop games, and im desperate with the issue. Please, advice

**Comment by pucgenie** [comment] 2022-01-03 21:17
Maybe related: The game causes my microphone to be effectively muted after a few minutes.
Exclusive mode unticked, so the root cause should be a bug in Windows because the game then shouldn't even be able to accidentally tinker with microphone settings.
Another game (Phasmo******) also causes the exact same symptoms to happen (voice recognition is the culprit there).

**Comment by itchyOwl** [comment] 2024-09-25 07:43
Old ticket with no known repro steps -> moving to candidates for removal. Could also move to QA investigates, but I don't think there's enough information for even that.

**Closed** 2024-10-28 10:50 UTC
Labels: Bug, Code
