### ISSUE TITLE
[Modding] if projectile isnt spawned by a weapon shot and has a hitscan="true" line, then the particles are not displayed correctly

### ISSUE THREAD

**Issue by Irradaven** [FakeFishGames/Barotrauma#10672] opened 2022-12-05 11:49 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

And to be more precise, they simply cease to be visually displayed if you are inside any hull.
Here we have this modded weapon create one projectile, what create more projectiles itself (like flakbolt from flak cannon):
![20221205161113_1](https://user-images.githubusercontent.com/97521293/205626026-28132d3d-e773-42e0-b951-4912ad746ce8.jpg)
As soon as you are inside any hull, tracers become invisible:
![20221205161018_1](https://user-images.githubusercontent.com/97521293/205626277-e61a2e7a-4bdd-4aef-8895-31832e265522.jpg)

This also applies to hitscan projectiles spawned by creatures -
Outside hull:
![20221205161302_1](https://user-images.githubusercontent.com/97521293/205627582-b97cca0e-7e90-4354-bc23-a87f62982ff3.jpg)
Inside hull:
![20221205161350_1](https://user-images.githubusercontent.com/97521293/205628297-77a15639-45c1-498c-a0ca-c2daab0b1a83.jpg)

### Reproduction steps

1. Copy code from flakbolt to any projectile;
2. Make the projectile that will be created from the original projectile hitscan, and give it tracer particle;
3. Profit.
Or
1. Change spineling projectile hitscan and give it tracer particle;
2. Give the spineling a ability to be inside hull;
3. Receive invisible hits while a creature swims inside hull;
4. Profit.

### Bug prevalence

Happens every now and then

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment] 2023-08-28 14:57
Tested.
Replaced handcannon rounds projectile code with flakbolt and giving it hitscan=true and laserbolt particle beam.
No issues with bots or clients firing.
Closing ticket.

**Comment by Jasontti** [comment] 2023-08-29 12:34
Upon further testing the problem is still present.

Outside of the hull secondary tracers are visible:
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/43e020f0-8a1c-44f1-ba00-39a7f0d88309)

Inside they're not:
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/a08e5f74-e5c2-4ec6-80f5-53cf0995b83b)

[Actually Handcannon.zip](https://github.com/Regalis11/Barotrauma/files/12464468/Actually.Handcannon.zip)

**Comment by Regalis11** [comment] 2023-12-20 09:27
Hopefully fixed for good now: https://github.com/Regalis11/Barotrauma-development/commit/a8f471ccae7cbd5970508cc7ec86cfb00079173b

**Comment by 3e849f2e5c** [comment] 2024-01-31 11:29
Tested, working properly now, can be closed

**Closed by 3e849f2e5c** 2024-01-31 11:29 UTC
Labels: Bug, Code, Modding
