### ISSUE TITLE
RequiredAngleToShoot uses a non-target limb to calculate the angle, which causes DenfenseBot to always become stuck randomly.

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13044] opened 2023-11-16 13:12 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I set RequiredAngleToShoot to 15, it looks like this:
https://github.com/Regalis11/Barotrauma/assets/73634685/6004dc88-776b-4fb5-a246-0d382815f560

### Reproduction steps

1. Make a mod and test

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by zhu-rengong** [comment] 2023-11-16 13:15
DefenseBot's shooting is very strange.
https://github.com/Regalis11/Barotrauma/assets/73634685/6c236fc8-1177-4f22-9a2f-9b3bb1cee715

**Comment by Regalis11** [comment] 2023-11-16 17:02
Thank you for the report!

It doesn't actually use any limb to calculate the angle, it just aims at the position of the character. It seems the issue is that when the RequiredAngleToShoot is very low, the character has trouble getting the aim close enough to fire. Since these kinds of ranged monster attacks use the procedural animations for aiming, they're inherently pretty inaccurate, and getting them to aim with this kind of precision most likely requires very careful tuning of the animation parameters (especially AimRotationTorque, and the mass and maybe angular damping of the limb that does the aiming).

**Comment by zhu-rengong** [comment] 2023-11-16 17:52
I adjusted RequiredAngleToShoot to a very high value, but since its angle calculation starts from the character's position rather than the limb, this problem still occurs in some cases, even if the adjustment is very fine.

**Comment by Regalis11** [comment] 2023-11-16 17:58
That shouldn't be the case actually, the angle calculation should start from the limb that does the firing. See https://github.com/Regalis11/Barotrauma/blob/71b710641b6b3df60d03adf0dab772b6f5def528/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/EnemyAIController.cs#L2277C4-L2277C4 and https://github.com/Regalis11/Barotrauma/blob/71b710641b6b3df60d03adf0dab772b6f5def528/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/EnemyAIController.cs#L2007.

By default, the "reference limb" is the one the attack is defined in, but that can be overridden using the property `RotationLimbIndex`. Could it be there's an issue with how that's configured in your mod, perhaps `RotationLimbIndex` is pointing to an incorrect limb?

**Comment by zhu-rengong** [comment] 2023-11-16 18:03
My RotationLimbIndex(bind to gun) is correct. Now the angle is calculated from the limb specified by RotationLimbIndex to the position of the target character, not to the position of the target limb.

**Comment by zhu-rengong** [comment] 2023-11-16 18:04
`toTarget` is a Character, not a target limb

**Comment by zhu-rengong** [comment] 2023-11-17 06:53
This comment say
https://github.com/Regalis11/Barotrauma/blob/71b710641b6b3df60d03adf0dab772b6f5def528/Barotrauma/BarotraumaShared/SharedSource/Characters/Attack.cs#L94
If TargetLimbType="None" then robot will get the closest limb, but the actual case is not:
https://github.com/Regalis11/Barotrauma/assets/73634685/6c8ff8e3-771d-41f7-bd4b-79e27fb31498
The closest limb should be my leg, but the defense bot always points at my torse(Maybe?)

**Comment by zhu-rengong** [comment] 2023-11-17 08:02
I adjusted again and again, now it looks like no problems now.

**Comment by zhu-rengong** [comment] 2023-11-17 08:35
I understand why it becomes so difficult to aim. `PhysicsBody:SmoothRotate()` only uses proportional control. When the ranged limb is close to the target angle, there may not be enough torque to drive. This results in you needing to adjust the AimRotatingTorque to a very high level. But the price is that the movements of the limbs will become very rough.

**Comment by Regalis11** [comment] 2023-11-17 09:24
Oh, you're right! Not being that familiar with this part of the code, I just assumed it's targeting and aiming at the character. But it does seem like that's not the case, and becomes very noticeable when changing `TargetLimbType` to something else.

It seems like the issue of getting stuck is not caused by this - since the bot aimed at the character, and also did the angle calculation based on the position of the character, it should have worked. So it seems like the issue is actually just that the animation system isn't precise enough to reliably get the aim to be accurate enough.

Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f55b510e8d576953ed7c02895842535cef0e7521

**Comment by zhu-rengong** [comment] 2023-11-17 14:12
Consider adding PID control to `PhysicsBody:SmoothRotate()`? At present, it only uses proportional control, which makes the aiming always have a fixed fatal error. It is also difficult for us to adjust the AimRotatingTorque to let the robot correct the angle of its own turret.

**Comment by zhu-rengong** [comment] 2023-11-17 14:34
Ranged weapons can force aiming regardless of the angle of the limbs, look this:
https://github.com/Regalis11/Barotrauma/assets/73634685/1aa81a35-c4db-4429-836d-2ffdd898e2b0
right thing is rightarm while green is right hand
so I can only implement it through limbs.
And it can't be an item, I know Turret has `AutoOperate`, but it can't fire indoor.

**Comment by Regalis11** [comment] 2023-11-17 15:38
> I know Turret has AutoOperate, but it can't fire indoor.

Are you sure? [That used to be the case](https://github.com/Regalis11/Barotrauma/issues/12233), but that bug should be fixed already.

**Comment by zhu-rengong** [comment] 2023-11-17 15:59
Wow, it does work, but it seems to only work in campaign and svs, not indoor pvp(cqb & cqc). However, my idea is completely exceeded out of vanilla.

**Comment by zhu-rengong** [comment] 2023-11-17 16:48
Thank you all for your patience in helping me answer my questions and solve many problems.
Although my OCD is not cured and they have some flaws, overall, those are minor minor minor issues.

**Comment by Jasontti** [comment] 2024-01-29 14:13
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4669/commits/2dc6437c4ab63f341f31da5a8b53144c1073d501

Changed `TargetLimbType` in defencebot to other things than `none` and everything seemed to work
Tested vanilla behaviour of defencebot and other creatures that use `TargetLimbType`

No issues found
Closing ticket

**Closed by Jasontti** 2024-01-29 14:13 UTC
Labels: Bug, Code
