### ISSUE TITLE
Terminal renders newline as boxes (since 1.0.13.1)

### ISSUE THREAD

**Issue by ralfbiedert** [FakeFishGames/Barotrauma#11978] opened 2023-05-10 16:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the latest patch (1.0.13.1) the terminal renders newline characters as small boxes:

![Screenshot_2](https://github.com/Regalis11/Barotrauma/assets/301288/2ce66fdb-1739-4a8c-8df2-3a0a558bee68)

In all previous versions they were invisible. 

### Reproduction steps

1. Send multi-line text to terminal (e.g., via Regex component)
2. Open terminal 

### Bug prevalence

Happens every time I play

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-05-11 14:05
I'm afraid I could not reproduce this. Tested by making a memory component input "[some text]\n" into the terminal, and the newline doesn't seem to be rendered.

![image](https://github.com/Regalis11/Barotrauma/assets/14351070/3a9f571f-aa66-4317-b3f9-c0e02105e408)

What are you using as the newline symbol?

**Comment by ralfbiedert** [comment] 2023-05-11 20:15
Inspecting the XML it appears to be `0xd 0xa` ([ship.zip](https://github.com/Regalis11/Barotrauma/files/11455946/ship.zip))

```
    <RegExFindComponent MaxOutputLength="200" Output="\n&#xD;&#xA;1. Suits in lockers&#xD;&#xA;2. Guns have ammo&#xD;&#xA;3. Ship repaired&#xD;&#xA;4. Emergency lockers full ('elocker')&#xD;&#xA;5. Dive kits full ('divekit')&#xD;&#xA;6. Cabinets sorted&#xD;&#xA;7. No items on floor&#xD;&#xA;8. Electrical: all &quot;green&quot;" UseCaptureGroup="False" FalseOutput="" ContinuousOutput="False" Expression="^prep$" PickingTime="0" CanBePicked="False" AllowInGameEditing="True" Msg="" />
```

When I update the text I usually copy it from a master `README` (UTF-8) opened in VSCodium on Windows, and paste it into the RegEx component. That said, I haven't updated these texts for quite a while now.

...

Ah, just realized, you explicitly put in `\n`, I just pasted a text block like this verbatim into the field:

```
Kit:

[ Scooter ] [ Plasma ] [ Belt ]

Belt:

[ Oxygen+  ] [ Flares   ]
[ Knive    ] [ Sonar    ]
[ Bandage+ ] [ Saline+  ]
```

**Comment by itchyOwl** [comment] 2024-05-03 07:26
Closing, because can't repro.

**Closed by itchyOwl** 2024-05-03 07:26 UTC
Labels: Bug, Code
