### ISSUE TITLE
[Unstable] Predefined labels are gone

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13551] opened 2024-03-14 02:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There should be a list of predefined labels here, but they're gone

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f3570cee-b0ef-4f91-b358-c618b56c8241)

### Reproduction steps

a

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-03-14 07:09
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13492

**Closed by Regalis11** 2024-03-14 07:09 UTC
