### ISSUE TITLE
Humanhusk crouch animation breaks the appendage ragdoll

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13300] opened 2024-01-12 23:29 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the humanhusk attacks, it consistently goes into crouching animation, tilting its head backwards and breaking the ragdoll of the appendage tentacles. 

You can see it here; both the vanilla and a modded version of the appendage

https://github.com/Regalis11/Barotrauma/assets/73229309/45356e31-5c48-4db6-a436-a2caae57fabc

### Reproduction steps

Control a humanhusk and spam crouch

or

1. spawn humanhusk
2. extend your arm by aiming below (the husk will target the arm below head level )
3. husk spazzes out

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/27ce946b-144b-4559-9394-c70fa50fe368)

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by itchyOwl** [comment] 2024-04-15 13:30
The appendage is quite restless, agreed, but couldn't actually break the ragdoll.

I don't think there's an easy way to fix this, and as the issue is very marginal, I'm closing the ticket.

**Closed by itchyOwl** 2024-04-15 13:30 UTC
Labels: Bug
