### ISSUE TITLE
Multi monitor selection issue

### ISSUE THREAD

**Issue by rhinotastic** [FakeFishGames/Barotrauma#1956] opened 2019-12-28 19:49 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a multimonitor setup i have to switch the resolution to a lower one, then set to windowed, drag the windo to the desired screen. then set full screen and resolution again.
Using standard windows control for moving application windows to different screens does not work
(windows key+shift+directional arrow key)

**Steps To Reproduce**
have 2 monitors, game always opens on main monitor. try get game to be on 2nd monitor without messing about with resolutions and unfullscreening. windows key+shift+arrow key towards 2nd monitor(left arrow for me) does not work as expected.

**Version**
v0.9.6.0 windows 10 64bit. build 17763.914

**Additional information**

**Comment by itchyOwl** [comment] 2020-01-07 19:57
So the issue is that if you switch from the larger resolution display to the lower resolution display with windows key + shift + arrow towards the lower resolution display the resolution does not change but stays too high for the selected display. After this you cannot change back to the main display with larger resolution?

Another thing is that currently the game always starts on the default monitor. You can change the default monitor in the OS display settings, but you cannot change the monitor from the in-game settings. I think we should allow changing the display in-game.

**Comment by rhinotastic** [comment] 2020-01-08 16:20
> 
> 
> So the issue is that if you switch from the larger resolution display to the lower resolution display with windows key + shift + arrow towards the lower resolution display the resolution does not change but stays too high for the selected display. After this you cannot change back to the main display with larger resolution? This I was able to reproduce.
> 
> Another thing is that currently the game always starts on the default monitor. You can change the default monitor in the OS display settings, but you cannot change the monitor from the in-game settings. I think we should allow changing the display in-game.

For me the issue is windows key + shift + arrow key does nothing for this only but works for everything else. both monitors are the same resolution 1920x1080.
Can you confirm that using the above key combination works under windows 10 with the barotrauma window for you? (are you using windows 10?)

**Comment by itchyOwl** [comment] 2020-01-09 08:57
Yes it does work for me, but as I described, it seems a bit bugged when moving the windowed game screen from a higher resolution display to a lower resolution display. Moving the game window from lower to higher works as it should.

**Comment by rhinotastic** [comment] 2020-01-09 11:32
interesting. After you confirming the key combination works for you i decided to play around with my settings.
Turns out it's to do with the scaling difference for the monitors.
![image](https://user-images.githubusercontent.com/47990498/72064031-ea153200-32d2-11ea-96ca-050297e7527d.png)
my main monitor has 125% but my 2nd monitor has 100%. So it's something to do with scaling that this application window doesn't like where as others maybe readjust but allow the transition.

**Comment by JoneKone** [comment] 2020-10-05 11:01
So I have 2 different resolution monitors :) 1440p and 1080p Also I'm on Linux Ubuntu 20.04.

I have same issues as the Original post describes.

`
![Screenshot from 2020-10-05 13-52-16](https://user-images.githubusercontent.com/1114115/95071977-2c10be80-0713-11eb-84a1-e7e98983bbf8.png)
![Screenshot from 2020-10-05 13-50-19](https://user-images.githubusercontent.com/1114115/95071981-2f0baf00-0713-11eb-8217-3b3180a6b02f.png)
![Screenshot from 2020-10-05 13-49-53](https://user-images.githubusercontent.com/1114115/95071995-3337cc80-0713-11eb-828f-ed26c24491bf.png)
`

**Comment by JoneKone** [comment] 2020-11-03 04:55
This should be a feature request, a monitor selector setting, so it will start at the correct monitor and all these issues can be fixed.

**Comment by jimj316** [comment] 2021-05-18 18:02
I also have the same issue on Linux - the screen resolution does not change after switching monitors, which I sometimes have to do (Barotrauma opens on the monitor with the cursor).

My suggested fix would be to change the game resolution if the window size changes while in borderless fullscreen mode.

**Comment by Regalis11** [comment] 2024-11-19 14:45
This has finally been addressed in our private repo, fix coming up in the next unstable build and the upcoming release.

**Closed by Regalis11** 2024-11-19 14:45 UTC
Labels: Bug, Code
