### ISSUE TITLE
If crew died during the round they are not restore on restart

### ISSUE THREAD

**Issue by Xardion495** [FakeFishGames/Barotrauma#13195] opened 2023-12-18 20:43 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

During the play in multiplayer with a teammate lost all crew (bots) in last fight with abyss creature. When we restarted round, all our bots are gone.
I restored campaign progress from backup and make another check. I killed some bots by kill command and initiate round restart. Killed bots are not restoring back.

Barotrauma Dedicated Server 1.2.6.0 (ReleaseLinux)
Ubuntu 22.04.3 LTS x64

### Reproduction steps

1. Play multiplayer campaign
2. Lost some bots
3. Restart the round
4. Check that dead bots are not coming back

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment] 2023-12-20 10:55
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. How exactly did you initiate the restart, by returning to the lobby and continuing? What kind of mods are you using? I wonder if some of those could have something to do with the issue.

https://github.com/Regalis11/Barotrauma/assets/14351070/00929a2a-04fe-4514-9c03-3c19ade3e88f

**Comment by Xardion495** [comment] 2023-12-20 22:07
I will enable logging on the next game and provide details tomorrow.
Mods which changing core game elements we using: Lua for Barotrauma, CsForBarotrauma, PerfomanceFix,  Barotraumatic, DynamicEuropa
Other ones are just add some contents.

**Comment by Xardion495** [comment] 2023-12-21 07:45
Funny, i can't reproduce it too now. If i remember correctly after the last bug happens i removed [Wifi Camera](https://steamcommunity.com/sharedfiles/filedetails/?id=3020618603) and [More Level Content](https://steamcommunity.com/sharedfiles/filedetails/?id=2814493175) mods. One of them (or both) causes server performance leak.
In case of future precedents i leave here a logfile. There are spawn data errors, but they are not affecting to gameplay.

**Comment by Xardion495** [comment] 2023-12-21 07:45
[debug.log](https://github.com/Regalis11/Barotrauma/files/13737519/debug.log)

**Comment by SomeRandomNoobKekeke** [comment] 2023-12-21 14:53
@Xardion495 
The log says that mod list was different, if you are running server from standalone lua build it probably has its own config_player.xml and it's own mod list
I would guess that it was caused by "Staying Smart"

**Comment by Regalis11** [comment] 2024-01-29 10:19
No known steps to repro, closing

**Closed by Regalis11** 2024-01-29 10:19 UTC
Labels: Bug, Need more info
