### ISSUE TITLE
MissionAction always chooses the same mission when modded missons included.

### ISSUE THREAD

**Issue by AzureNocte** [FakeFishGames/Barotrauma#13564] opened 2024-03-16 16:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I noticed that when there are modded missions included, you will always get the same mission from outpost manager regardless the commonness of each mission. 
I uploaded the creature mod I made which includes many Monstermissions, Nestmissions, Alienruinclearmission etc, I added the right tags for them yet some of them could never be picked which is really frustrating for me...

[RE_Creatures of the Depth.zip](https://github.com/FakeFishGames/Barotrauma/files/14624318/RE_Creatures.of.the.Depth.zip)

### Reproduction steps

1. enter outpost, go to outpost manager.
2. press F3, enablecheats and triggerevent missionevent_killswarm_set1/2/3/4, missionevent_killmonster_set1/2/3/4, etc.
3. quit round, restart and repeat.
4. always get same missions.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-03-17 10:26
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13234

**Closed by Regalis11** 2024-03-17 10:26 UTC
