### ISSUE TITLE
Custom Skills dont appear in skill info after changing levels

### ISSUE THREAD

**Issue by ricky122122** [FakeFishGames/Barotrauma#13058] opened 2023-11-19 04:08 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Custom skills when the round changes wont appear until the player gains a skill point then it reappears as if your gaining it again

### Reproduction steps

start a campaign
enablecheats and use setskill test 50
change levels and check skill info not their
use setskill medical 1
watch as you gain 1 in medical and 50 other points also appear magically 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-19 13:10
Thank you for the report! I'm afraid I could not reproduce this, the skill seems to appear as soon as I use the console command:

https://github.com/Regalis11/Barotrauma/assets/14351070/14455b79-9664-4eaf-a0f4-063496404f02

I wonder if this could have something to do with the mods you're using? If you're using source code mods, it could be some of them modify how the skills are handled in some way.

**Comment by ricky122122** [comment] 2023-11-19 14:37
You misunderstood it only vanishes after round change like in campaign

**Comment by Regalis11** [comment] 2023-11-21 17:17
Thank you for the clarification! I was able to repro the issue now, but it seems like this only happens in multiplayer: I couldn't get it to occur in single player by following those steps.

**Comment by Regalis11** [comment] 2023-11-21 17:23
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/18d4286ea68296b502f22c11702d01ec57b671a2 (commit in our private repo)

**Comment by 3e849f2e5c** [comment] 2024-01-24 14:14
Tested in multiplayer, skills were properly persisting between rounds

**Closed by 3e849f2e5c** 2024-01-24 14:14 UTC
Labels: Bug, Code, Low prio, Modding
