### ISSUE TITLE
The stock number of items shown in the shop does not correspond to what I am owned.

### ISSUE THREAD

**Issue by pavel4win** [FakeFishGames/Barotrauma#12712] opened 2023-09-24 08:09 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The stock number of items shown in the shop does not correspond to what I am owned.
I used LUA mod shows how many items on my ship. Additionally, I remember how many helmets I have. Exactly six on the heads of my people.
I notice this bug in almost every game. Both in multiplayer and in single player. It seems that some items were counted twice. The discrepancy is always on the larger side.

![2023-09-24_10-55-33](https://github.com/Regalis11/Barotrauma/assets/47295383/2d06adbb-0cd3-45a7-a1d9-908d0fb49363)
![2023-09-24_10-56-44](https://github.com/Regalis11/Barotrauma/assets/47295383/1b2ddbd4-fccf-4dfd-84d8-2c279240401f)

I apologize for the unnecessary information in the second screenshot. The picture unexpectedly included a screenshot of my fourth monitor, just wipe it out.
Important information is in "search item" window.

Important addition! 
When I saved and exited the game, and then loaded the saved game, the number of my helmets shown at the merchant began to correspond to their real number. 
This means that an error in item counting occurs and accumulates during the game.

### Reproduction steps

I do not know how to reproduce. I just send you my save game file.

[o2023.zip](https://github.com/Regalis11/Barotrauma/files/12708080/o2023.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-09-24 15:29
Thank you for the report! I gave the provided save a test, but unfortunately couldn't find a way to get the store interface to display an incorrect number of items. Something to note is that the "owned" count also includes items you've purchased during the round (even if they haven't been delivered yet), I wonder if that could've caused the discrepancy? You also mentioned you're using a LUA mod that shows how many items there are on the ship - which mod is that specifically (wondering if it could have something to do with the issue)?

I used LUA mod shows how many items on my ship

**Comment by BlackMoons** [comment] 2023-10-01 21:46
I feel like I experience this bug a lot in campaign. It may require actually playing campaign rounds and visiting multiple vendors to manifest. 

Last time I played it said I owned something insane like 170 shotgun shells for example. Most of the shotgun shells are on NPC's, but im pretty sure they only have about 70 between em. 

Any chance its counting items on station personal too? Seems like shotgun shells and riot helmets are something security guards might be carrying.

**Comment by pavel4win** [comment] 2023-11-03 22:16
> You also mentioned you're using a LUA mod that shows how many items there are on the ship - which mod is that specifically (wondering if it could have something to do with the issue)?

The mod is "item finder count"
https://steamcommunity.com/sharedfiles/filedetails/?id=2968260397
But this mod do not works anymore after 1.18 update.

**Comment by BlackMoons** [comment] 2023-11-03 22:51
It would be amazing if such a mod was stock. Like the built in item finder on the status monitor in the ship having a [5] (or whatever) next to each item name to indicate quantity on the ship.

**Comment by Regalis11** [comment] 2024-02-16 10:59
Most likely a duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13060

**Closed by Regalis11** 2024-02-16 10:59 UTC
Labels: Bug, Need more info, Code
