### ISSUE TITLE
Multiple NPC's on repair do a horrible job and fight each other for repair access.

### ISSUE THREAD

**Issue by BlackMoons** [FakeFishGames/Barotrauma#13041] opened 2023-11-16 04:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Multiple NPC's set to repair systems do a horrible job. Not only do they all run after the same broken thing, but in the server logs they spam you with hundreds of repair spam as they try to steal the job from each other. 

At the very least they should 'reserve' a system when actively repairing and other bots on repair should go repair something else, since only 1 person can repair a particular item at a time.

Ideally, the nearest bot should be called when something decays enough and others should ignore it. 

Maybe a simple change, could be: Bots only repair when condition has reached repair threshold minus a small factor based on distance to target.

IE, if repair threshold is 90% on an item, a bot in the same room will repair it when it hits 90%, but a bot clear across the sub might ignore it until it reaches 50%.

This would let players have a much better chance at actually repairing things as they decay and bots wouldn't seem so much better at repairing everything before you even know its started to decay (Making human mechanics/engineers frustrated that any bot can do their job WAY better then a human can), And on large ships with multiple bots, ideally all the bots wouldn't end up in the exact same position all chasing after the exact same items. Only the nearest bot would get called at first, and maybe more later if he somehow can't make it and the item decays further. Some items might even decay enough for players to see smoke/damage decals before a bot clear across the ship decides to repair it. 

This would also allow the 'broken devices' order to do something for NPC's, it would summon repair bots to go to that room, and then by being right in the room they would naturally repair anything that is even slightly below the 'repairable' threshold. (Or bots could consider any device in the room without the distance bias for their next repair task, and let the bot decide if there is anything to do in that room or not)

### Reproduction steps

Start a campaign.

Set multiple bots to repair

Break something or let something decay

Observe as all bots run for the same thing, then fight over who gets to actually repair it. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Micromot20** [comment] 2023-11-16 15:25
I was not able to reproduce the queueing issues with the steps given, for me they just chose the object(fuse boxes) that weren't being repaired by one of the other bots sa expected.

**Comment by Regalis11** [comment] 2023-11-16 17:40
Thank you for the report!

> Maybe a simple change, could be: Bots only repair when condition has reached repair threshold minus a small factor based on distance to target.

This is similar to how it works already: the bots prioritize which items to repair based on distance, their skills and how damaged the item is. I also gave this a quick test and couldn't reproduce the issue. When there's a single broken item, it seems all the bots start heading towards it, but they seem to leave the repairs to the most skilled one.

> but in the server logs they spam you with hundreds of repair spam as they try to steal the job from each other.

What kind of spam do you mean? Some lines said by the bots or some kind of error/warning messages?

**Comment by Regalis11** [comment] 2024-01-29 10:19
Insufficient information to address the issue, closing

**Closed by Regalis11** 2024-01-29 10:19 UTC
Labels: Need more info
