### ISSUE TITLE
Changing graphics settings disables voice chat

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#12644] opened 2023-09-08 11:00 UTC
### What happened?

When in multiplayer, changing the display mode (going from borderless to fullscreen, etc.), changing the resolution, or disabling/enabling vsync will disable voice chat until the settings menu is opened again. This occurs when using either push-to-talk or voice activity.

Disclaimer - I am not certain that it actually disables voice chat, but this does remove the little bubble above your character's head, so it's impossible to tell whether you are speaking or not.

### Reproduction steps

1. Host a multiplayer game
2. Open the settings menu, and change the game's resolution
3. Hit "accept"
4. Observe that pressing the push-to-talk key or talking into your mic will not show the speech bubble above your head
5. Open the settings menu
6. Close the settings menu
7. Observe that the speech bubble has returned

### Single player or multiplayer?

Only occurs in multiplayer

### Version

Stable (v1.0.21.0) & Unstable (v1.1.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment] 2023-09-13 10:37
Tested in v1.0.21.0

Reproduced this following the provided steps. The speech bubble above the players head and the audio indicator in the crew list do not appear after changing the resolution settings. Changing other graphical settings or audio ones didn't cause any problems, it just seems to be limited to the resolution change.

https://github.com/Regalis11/Barotrauma/assets/135589009/b6bb1750-de07-4e6c-b194-9ee571d581c7

Sending to be further investigated by the devs.

**Comment by Rokvach** [comment] 2024-04-09 01:20
Tested, working correctly. Can be merged and closed.

**Closed** 2024-04-09 07:41 UTC
Labels: Bug, Code
