### ISSUE TITLE
No audio input devices available

### ISSUE THREAD

**Issue by RagnarTheRagnar** [FakeFishGames/Barotrauma#9817] opened 2022-09-03 02:55 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Came back to the game after a bit of long break. Found that I had no audio. Further review shows that I have no input or output devices available.

I know for a fact I have a virtual input and output for my headphones. So they work in every other game I've tried so far. 

Console has the following: 
Error after assigning ALC context: Invalid device. Disabling audio playback...

### Reproduction steps

Idk if the audio setup I have is weird or unique. I found a few other random people mentioning issues here and there.

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error after assigning ALC context: Invalid device. Disabling audio playback...
```

**Comment by cookyt** [comment] 2022-09-05 23:10
I had this same issue earlier this week, but with my audio output device. I'm on Windows 11, and am running Barotrauma v0.18.15.1 (latest stable hotfix).

## What I think is happening

Barotrauma is caching the OpenAL device name for my Audio output device. The other night, I had to unplug my external audio interface, so was using the built-in motherboard's audio card. When Barotrauma tried to open what I had previously set as the default output device in Windows (i.e., my unplugged external audio interface), OpenAL threw an error and failed to initialize the audio sub-system.

Moreover, because of this error, Barotrauma isn't able to populate the list of alternative devices in the "settings" menu. So it's unfixable from within the UI.

## Work Around

The default audio output device is stored in the config XML file with the Game files in location:

    C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\config_player.xml

To fix this issue, I removed the setting `audiooutputdevice="OpenAL_some_long_string"` from my config file. I believe this caused Barotrauma to try to, instead, open the default device set for it on Windows, so the audio-subsystem fixed itself, and I could switch to the right output via the audio settings menu.

If you're having trouble w/ the microphone, you can probably delete the `voicecapturedevice="somestring"` line to have the same effect.

Here's an example snippet from my XML file:

```xml
<config
  language="English"
  .... other stuff ...>
  <audio
    musicvolume="0.3"
    ... other stuff ...
    <!-- DELETE THIS LINE -->
    audiooutputdevice="OpenAL_x0020_Soft_x0020_on_x0020_Main_x0020_Out_x0020_1_x002F_2_x0020__x0028_3-_x0020_Studio_x0020_24c_x0029_"
    voicecapturedevice=""
    ... other stuff... />
... other stuff ...
</config>


```

**Comment by RagnarTheRagnar** [comment] 2022-09-09 02:34
> I had this same issue earlier this week, but with my audio output device. I'm on Windows 11, and am running Barotrauma v0.18.15.1 (latest stable hotfix).
> 
> ## What I think is happening
> Barotrauma is caching the OpenAL device name for my Audio output device. The other night, I had to unplug my external audio interface, so was using the built-in motherboard's audio card. When Barotrauma tried to open what I had previously set as the default output device in Windows (i.e., my unplugged external audio interface), OpenAL threw an error and failed to initialize the audio sub-system.
> 
> Moreover, because of this error, Barotrauma isn't able to populate the list of alternative devices in the "settings" menu. So it's unfixable from within the UI.
> 
> ## Work Around
> The default audio output device is stored in the config XML file with the Game files in location:
> 
> ```
> C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\config_player.xml
> ```
> 
> To fix this issue, I removed the setting `audiooutputdevice="OpenAL_some_long_string"` from my config file. I believe this caused Barotrauma to try to, instead, open the default device set for it on Windows, so the audio-subsystem fixed itself, and I could switch to the right output via the audio settings menu.
> 
> If you're having trouble w/ the microphone, you can probably delete the `voicecapturedevice="somestring"` line to have the same effect.
> 
> Here's an example snippet from my XML file:
> 
> ```
> <config
>   language="English"
>   .... other stuff ...>
>   <audio
>     musicvolume="0.3"
>     ... other stuff ...
>     
>     audiooutputdevice="OpenAL_x0020_Soft_x0020_on_x0020_Main_x0020_Out_x0020_1_x002F_2_x0020__x0028_3-_x0020_Studio_x0020_24c_x0029_"
>     voicecapturedevice=""
>     ... other stuff... />
> ... other stuff ...
> </config>
> ```
> 
> ## Reproduce
> See "work around". If you change the `audiooutputdevice` setting to some arbitrary string and restart the game, you'll get the original error message.

Worked exactly as described. Thank you very much.

**Comment by itchyOwl** [comment] 2023-02-21 11:39
There's an apparently functional workaround in the comments above, but I think we should check the validity of the audio configuration and remove invalid definitions. Didn't check if we actually do it (in which case it could be bugged), so adding both "bug" and "code" labels and moving to bugfixes with the "low prio" tag.

**Comment by Regalis11** [comment] 2023-03-10 08:37
> Didn't check if we actually do it (in which case it could be bugged)

We do: [the settings menu should list the available audio devices](https://github.com/Regalis11/Barotrauma/blob/48c66adcdcb50d28d1b735218f5dbc10b9a971da/Barotrauma/BarotraumaClient/ClientSource/Settings/SettingsMenu.cs#L327), and default to the 1st one if the previously selected one could not be found.

I gave this a test, and unfortunately could not reproduce the issue. After disconnecting my primary audio device (speakers connected via USB), the game defaulted to my monitor's audio output instead, and I was also able to switch the device in the settings with no issues.

**Comment by Regalis11** [comment] 2024-02-16 11:02
Closing in favor of https://github.com/FakeFishGames/Barotrauma/issues/13430

**Closed by Regalis11** 2024-02-16 11:02 UTC
Labels: Bug, Need more info, Code, Low prio
