### ISSUE TITLE
Dedicated server description is cut down on the server browser

### ISSUE THREAD

**Issue by evilfactory** [FakeFishGames/Barotrauma#11043] opened 2023-01-27 15:41 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dedicated servers have their description cut down on the server browser, while on player-hosted servers this doesn't seem like a problem. I also noticed the server package list will show up as unknown when you have around +5 mods enabled, similar issue?

Server browser description
![Barotrauma_05RgqfqH6x](https://user-images.githubusercontent.com/36804725/215124685-44ada5e1-876c-4964-80ce-11281900fc36.png)
Description when connected to the server
![Barotrauma_ICaI9mgCIZ](https://user-images.githubusercontent.com/36804725/215124983-b5b5d4c4-b8a6-47f7-a1ae-01d1bcde71ca.png)

### Reproduction steps

1. Start a dedicated server
2. Set the description to something big
3. Notice description is cut down on the server browser

### Bug prevalence

Happens every time I play

### Version

0.21.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-02-22 08:02
I don't see why it's not scrollable in the browser description, so probably not intentional (?)

**Comment by evilfactory** [comment] 2023-03-06 14:56
I don't believe the problem is that the text isn't scrollable, the description seems to have been cut down by the steam server list (?).

**Comment by Xardion495** [comment] 2023-03-07 09:30
Still actual on 21.6 version in 'ALL SERVERS' tab. But in 'RECENT' tab server description always display full and actual info. By the way same concerns to the mods list

**Comment by Regalis11** [comment] 2023-03-07 19:57
Seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/11453: the value gets truncated to 255 bytes

**Comment by Rokvach** [comment] 2023-09-25 09:11
This doesn't seem to be an issue anymore, closing

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/b786eb13-3366-4757-bfd2-a86cc76624e4)

**Comment by Regalis11** [comment] 2024-10-31 13:28
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/ce21831a23440b76dc6813701f4282ca62fb4a88

**Closed** 2024-12-12 13:12 UTC
Labels: Bug, Code, Networking
