### ISSUE TITLE
Can't connect to steamP2P or public server

### ISSUE THREAD

**Issue by knight000** [FakeFishGames/Barotrauma#10156] opened 2022-10-26 13:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I try to link to any server (this includes localhost servers), it shows

> COULD NOT CONNECT TO THE SERVER. 
> Your name contains symbols disallowed by the 
> server host.Please enter another name in the 
> "Player name" field in the server browser

I tried changing my SteamName and PlayerName to English characters, like K, X, XxXxX or random English + numbers, and the problem still happens. But other people can access the SteamP2P server I have opened.

### Reproduction steps

1. Open the game
2. Join a server
3. COULD NOT CONNECT TO THE SERVER. 

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment] 2022-11-21 19:17
This issue is quite common within the community. I've seen several instances of this in the discord server's #tech-support channel, and it was brought up once again today. Today's problem had this error occur when a user used a name which included Korean characters, though many other instances cannot identify the cause. 

If this is a self-fixing issue, an explanation as to how would be greatly appreciated. I'd note it down so it could be sent to anyone who suffers these issues, however the fact this issue continues to show up pretty regularly makes me believe there's more to look into.

**Comment by Regalis11** [comment] 2022-11-28 18:22
> If this is a self-fixing issue, an explanation as to how would be greatly appreciated. I'd note it down so it could be sent to anyone who suffers these issues, however the fact this issue continues to show up pretty regularly makes me believe there's more to look into.

This issue happens because by default, the servers only accept certain Unicode characters in client names. The intention is to prevent clients from being able to use non-renderable special symbols in their names, which could otherwise be used to make the name appear invisible or make it extremely difficult to type the user's name for e.g. private messages or console commands. Something to note though is that your Steam username should make no difference here - the server only cares about the name chosen in the server list screen (and only that name is ever shown in-game).

It seems the unicode blocks for Korean characters are currently missing from the range of allowed default symbols. However, it seem strange that English characters would've been flagged as disallowed and I haven't found a way to reproduce that issue (unless the host had specifically disallowed English characters, which seems very unlikely).

**Comment by Wheatley1001** [comment] 2022-11-28 22:40
> Something to note though is that your Steam username should make no difference here - the server only cares about the name chosen in the server list screen (and only that name is ever shown in-game).

Does the server not use your steam name by default? I've always had my username default to "Wheatley1001" whenever I join a lobby. Could it be possible that players who have illegal characters in their steam name have those same characters blocked whilst trying to connect to a lobby?

**Comment by Regalis11** [comment] 2022-12-05 11:05
It uses whatever name you've entered in the "player name" field, which does default to your Steam username.

**Comment by Wheatley1001** [comment] 2022-12-05 13:55
Couldn't this lead to players with illegal characters in their steam names being unable to play unless they change their steam account name? 

I suppose the player name field could use a generic default that everyone has their name set to so that regardless of your steam name. Something as simple as "Player" with a larger emphasis on changing your name before the game starts. That way your steam name can't get you unintentionally "banned" from most servers. Of course, localisation may make this unappealing due to adding an extra thing to translate, but it's certainly an option.

**Comment by davethwave** [comment] 2023-03-15 04:04
I found one way to fix it is to restart steam itself if the problem isn't caused by the illegal characters. Dunno if this will help with others but it helped me.

**Comment by Snatchymon** [comment] 2023-04-08 10:09
If the problem is being caused by illegal characters you could try changing your name in the config file, found at:
C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\config_player.xml

What you're looking to change is:
name="YourName"

Just set what's in the quotations to whatever you want your new name to be using a text editor and save. Found at line 92 with all the other player stuff. Hope this helps :)

**Comment by Regalis11** [comment] 2023-08-21 12:42
I'm afraid there's probably not enough information here for addressing the issue. The name examples listed in the original report seem to work with no issues, so there cause must be somewhere else.

If anyone runs into this issue again, a report with the config file (C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\config_player.xml) attached might give us some more clues for addressing this.

**Comment by Regalis11** [comment] 2024-01-12 14:26
Found a way to reproduce this now.
1. Change the name in config_player.xml to `"다정s아라⢃대현"`
2. Try to join a server
3. Try to change the name to something else in the server lobby: doesn't work, the invisible braille symbol (`⢃`) doesn't get removed.

**Comment by Regalis11** [comment] 2024-01-12 14:35
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f87c586bb1f2d0e07f35e7acb9a15c6059136c6b

**Comment by Jasontti** [comment] 2024-02-20 14:26
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4844/commits/616d12fab8b3fafe02745a925dff745b8285ea65

Used example above, got warning and name changed automatically
Tried to paste that as a name in server browser
Tested japanese, chinese, korean(hangul) and russian

Vietnamese Hán-Nôm 𡨸儒 gave this, but removed bad character without problems when edited in to config_player.xml:
![image](https://github.com/FakeFishGames/Barotrauma/assets/8488224/833b5c70-b00d-43da-8581-c905672ba666)

No issues found
Closing ticket

**Closed by Jasontti** 2024-02-20 14:26 UTC
Labels: Bug, Code
