### ISSUE TITLE
AMD RX 7600 - degraded performance

### ISSUE THREAD

**Issue by lewri** [FakeFishGames/Barotrauma#12158] opened 2023-06-14 17:50 UTC
Edit: No change with v1.0.21.0
Edit2: AMD Driver 23.7.1 no change

### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<ins>I'm quite certain this is AMD's fault</ins> but I thought it would be worth noting that the newly released AMD RX 7600 appears to have performance problems in Barotrauma outside of game menus. Other games/benchmarks appear to be operating fine.

Previously I used an RX 580 (which I think Regalis actually uses) and the framerate would keep up find with my vsync refresh rate of 144fps in all scenarios.
However, the RX 7600 card now causes drops in settlements sometimes to ~20fps (especially the fancy neon ones), with an average 40-70fps in general.

I did do a full reset of my drivers/software but this didn't resolve.
(I have also reported this to AMD too for sake of completeness, their [current driver - 5/24/2023](https://www.amd.com/en/support/graphics/amd-radeon-rx-7000-series/amd-radeon-rx-7600-series/amd-radeon-rx-7600) was dropped a little before the card launched and not updated yet)

This could also be an aligned duplicate of #9396 

### Reproduction steps

Load a settlement or mission

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by lewri** [comment] 2023-08-03 21:19
Hi there!
So outcomes (all 1080p):
Standard setup: Vsync on, Borderless windowed - 40-80fps
Fullscreen, Vsync - No change
Windowed, Vsync - No change
Fullscreen, vsync off - No change

Very peculiar. AMD released another driver update this week so I will update it again and edit this post with any differences.

**Comment by lewri** [comment] 2023-08-13 11:33
Thanks for waiting.
I've updated the graphics driver today to the latest version -- there's still no change in performance.
What is weird though, is my very old early access save I abandoned actually runs around 20fps better than the new save I made post 1.0. (that old save being the old with the old stairs logic)

**Comment by Regalis11** [comment] 2023-08-21 12:16
Thank you for the extra information!

I have a feeling this might not actually be an issue with the GPU or rendering performance. It's a known issue that large outposts with lots of NPCs can sometimes cause a performance drop, and since you mentioned this happening in settlements in particular, I think that's a likely culprit. There were some issues in the AI that caused an unnecessary performance hit, which we've since patched, but if you're still experiencing poor framerates, the problem might be somewhere else.

Something that might give us more clues for diagnosing this is a screenshot with the performance statistics overlay visible (which can be enabled using the console command `showperf`). The save file might also be helpful, in case there's something specific in that save that's degrading the performance. Thanks and sorry for the inconvenience!

**Comment by lewri** [comment] 2023-09-02 15:40
Hey Regalis,

Sorry for the wait. Screenshot with the overlay included.
![20230902163336_1](https://github.com/Regalis11/Barotrauma/assets/20030128/adfaedb2-69a5-415f-a286-54642e2d58ef)

Regarding settlements -- the frame drop can also happen during a quite intense event when shooting multiple creatures outside the ship -- sometimes even worse to 30 fps.

My current savegame is attached here: [New.zip](https://github.com/Regalis11/Barotrauma/files/12504254/New.zip)

The very old save I mentioned is likely still available from https://github.com/Regalis11/Barotrauma/issues/10206#issuecomment-1400840135

All the best =]

**Comment by lewri** [comment] 2023-12-24 16:08
An update for you on this regarding the Winter patch. Framerate is around the same but a little more stable to the higher end. 
In multiplayer server, the framerate seems to perform much better (around 100-120) but that could be due to less players/bots (7 bots in single vs 3 bots in multi).

**Comment by Regalis11** [comment] 2024-02-16 10:11
Closing as a duplicate of https://github.com/FakeFishGames/Barotrauma/issues/9396 (seems likely that this is not related to rendering performance, but a more "general" performance issue caused by large numbers of NPCs)

**Closed by Regalis11** 2024-02-16 10:11 UTC
Labels: Need more info, Performance
