### ISSUE TITLE
Save Corrupted after undocking from outpost 

### ISSUE THREAD

**Issue by Kadachikotel** [FakeFishGames/Barotrauma#13442] opened 2024-02-17 17:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

after undocking from outpost the game does not load in again and keep saying that "saved submarine is empty. The subamrine file may be corrupted." 

### Reproduction steps

![obraz](https://github.com/FakeFishGames/Barotrauma/assets/160341877/65c43a7f-664a-4517-aeef-04d581924e29)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Kadachikotel** [comment] 2024-02-17 22:13
I tried to fix it by changing the submarine to older one on the same same save and it work but after trying to change it on station the ship duplicated and you couldn't load neither of them so i guess there goes my ship but still can normaly play the campaign normally.
![obraz](https://github.com/FakeFishGames/Barotrauma/assets/160341877/ec721c1f-36cc-42ae-a091-44139ef4dfa2)

**Comment by itchyOwl** [comment] 2024-02-29 16:39
Duplicate of #12104?

**Comment by Regalis11** [comment] 2024-03-01 11:46
Closing as a duplicate of https://github.com/FakeFishGames/Barotrauma/issues/12104. Since there's now several reports about this, I think we need to bump up the priority on figuring out the cause to this.

**Closed by Regalis11** 2024-03-01 11:46 UTC
Labels: Bug, Code
