### ISSUE TITLE
Diagonal hitboxes of some blocks cause blaunt traumas

### ISSUE THREAD

**Issue by libralocis** [FakeFishGames/Barotrauma#13370] opened 2024-02-01 17:25 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well i found this bug while playing with my own submarine and suddenly i caught damage out of nowhere. I went to submarine editor and messed around with my sub to find the trouble. And so i found out that for some reason when diagonal hitbox collides with a normal square one it pulls the player in the blocks ( i suspect it is the root of the trouble) and then player take damage. And so making stairs without actuall stairs or platforms is dangerous wich wasn't the case with older versions where it worked fine.

### Reproduction steps

1. Find/make a 2 solid blocks where one is diagonal and the other is not ( for more consistency put more diagonal blocks in normal one )
2. Run/walk on the structure
3. Get pulled in the structure and omnomnomed in the process
4. profit
![изображение_2024-02-01_202509944](https://github.com/FakeFishGames/Barotrauma/assets/138250659/62225e18-838b-4776-b720-d3bd092db550)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment] 2024-02-02 07:10
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13240

**Closed by Regalis11** 2024-02-02 07:10 UTC
