### ISSUE TITLE
Disconnected due to an error: "Message byte position incorrect after reading an event.."

### ISSUE THREAD

**Issue by godofcoriander** [FakeFishGames/Barotrauma#12390] opened 2023-07-22 13:03 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/140253776/de105ada-d598-4c33-a9fb-a71a0c341889)
Not quite sure what happened to the game because I can't understand the code/command showed in the screenshot. What I know so far is that every single time I want to join in my friend's game, I get kicked out for unknown reason. Please kindly help me identify the reason and hopefully there would be a solution to it. I've tried to reinstall the game & mods to improve the situation, but it seems this doesn't help at all. I still keep getting kicked out.

### Reproduction steps

1. join in my friends server.
2. The host start the game
3. After few sec I joined the game, I got kicked out
![image](https://github.com/Regalis11/Barotrauma/assets/140253776/de105ada-d598-4c33-a9fb-a71a0c341889)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2023-08-01 10:54
Looks similar to #12084, which was closed as non-reproducible. We'd need the steps to repro this. 

Does it _only_ happen when you try to join your friend's server or when trying to join _any_ server? You wrote that "every single time I want to join in my friend's game, I get kicked out for unknown reason.", yet under "bug prevalence" the issue is reported to "happen every now and then".

Are there any mods involved?

**Comment by Regalis11** [comment] 2024-01-25 09:58
Insufficient information to address the issue, closing

**Closed by Regalis11** 2024-01-25 09:58 UTC
Labels: Bug, Need more info, Code, Networking
