### ISSUE TITLE
Salaries induce frustration from requiring constant attention

### ISSUE THREAD

**Issue by WJohn** [FakeFishGames/Barotrauma#13444] opened 2024-02-17 23:48 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Salaries require the Captain to manually adjust the percentages for each and every player who joins the server, and are reset every time they die. Over the course of a campaign with players coming and going and dying and respawning, this can require the Captain to manually set Salaries upwards of 200 times. This process becomes frustrating enough to ignore using the system entirely, depriving the entire crew of their wages and the wallet mechanic its purpose.

Ideally, some kind of Default Salary slider should be available to the Captain (or whoever has server permission to adjust Salaries). This would simply set the default salary of a newly joined player to whatever percentage the Captain wants, which can later be manually adjusted. Additionally, players who die should have their current Salary values preserved after death, so that the Captain doesn't have to re-adjust their suddenly changed pay.

Mockup example:
![default salary](https://github.com/FakeFishGames/Barotrauma/assets/5988156/96954d1e-cc6c-49d5-8c71-95999bb17d82)

### Reproduction steps

1. Start a multiplayer campaign in a public lobby
2. Observe the default 0% Salary of newly joined players
3. Manually adjust the Salary of each player who joins over the course of the campaign
4. Observe whether Salaries reset upon player respawn

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment] 2024-03-19 12:53
- [ ] Received this error when launching dedicated server
![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/c8490063-79ea-4303-88ec-8eda950b0e51)

- [ ] New campaign default salary setting feels a bit too hidden, should be better to have it as a part of campaign setup. 

![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/b927e6f6-fb55-4b0d-88b6-dd914ea94b42)

- [ ] Having a way to force the default salary to change on existing players would be nice, currently if the setting is changed it only affects newly joining players. Could be a toggle next to the slider or a button to force it.

**Comment by giists** [comment] 2024-04-15 15:20
When resetting the salaries of every player, the salary slider moves to the correct position, but the value stays as the last value that was manually set.
![image](https://github.com/FakeFishGames/Barotrauma/assets/35175875/91d89542-edee-4109-b24e-bd30e7c87db4)

**Comment by giists** [comment] 2024-04-16 14:17
Everything work as intended.

**Comment by Rokvach** [comment] 2024-04-18 08:07
- [ ] Default salary setting in server settings is missing a text, I also feel like the setting should be somewhere else now that the settings have been categorized, either in round management or gameplay
![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/03268cd7-09d9-4d17-b029-6c3a114d2664)

Should there be a text here also? 
![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/907094c3-8182-4abe-9512-0102539f3297)

- [ ] Just found a it a bit odd that we specify online players here, could just be players
![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/d0f8020c-e94d-4e96-8510-632d239fb5c4)

**Comment by 3e849f2e5c** [comment] 2024-04-29 05:43
Added the texts back, no idea where they went and couldn't even find them in git history

**Comment by Rokvach** [comment] 2024-05-06 07:36
Tested, working correctly. Can be merged and closed.

**Closed** 2024-05-06 07:42 UTC
Labels: Feature request, Code
