### ISSUE TITLE
Broken diving suit spawns oxygen bottles each new round

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#13341] opened 2024-01-23 16:30 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If broken diving suit is empty (doesnt have oxygen bottle) and you continue to next level in campaign - it will spawn a new oxygen bottle in it

### Reproduction steps

1. start campaign
2. spawn broken diving suit and take out oxygen bottle
3. proceed to next level
4. check inside suit

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-23 16:32
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13221

**Closed by Regalis11** 2024-01-23 16:32 UTC
