### ISSUE TITLE
Game crashes after about 20 minutes in mission constantly

### ISSUE THREAD

**Issue by user8428294** [FakeFishGames/Barotrauma#13368] opened 2024-02-01 08:26 UTC
Im playing modded campaign after some time not entering barotrauma, but now with the same mods I used 3 months ago constantly have game crashing about 20 minutes in, as the title says. Here is a crash report generated, hope someone can help.

[crashreport.txt](https://github.com/FakeFishGames/Barotrauma/files/14122245/crashreport.txt)

**Comment by Regalis11** [comment] 2024-02-01 09:02
This seems to be a bug caused by Neurotrauma. I'm afraid there's not much we can do to address issues caused by code modifications in a mod. :/ Sorry for the inconvenience.

Closing as a duplicate of [Game crashes 20-30 minutes after entering the game.](https://github.com/FakeFishGames/Barotrauma/issues/13315)

**Closed by Regalis11** 2024-02-01 09:02 UTC

**Comment by user8428294** [comment] 2024-02-01 09:03
> This seems to be a bug caused by Neurotrauma. I'm afraid there's not much we can do to address issues caused by code modifications in a mod. :/ Sorry for the inconvenience.
> 
> Closing as a duplicate of [Game crashes 20-30 minutes after entering the game.](https://github.com/FakeFishGames/Barotrauma/issues/13315)

Thanks, will do that then
