### ISSUE TITLE
Circuit box issues - Update Performance, Corruption, Inconsistencies 

### ISSUE THREAD

**Issue by JimmySlickD** [FakeFishGames/Barotrauma#13499] opened 2024-02-29 15:36 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After using the Circuit box i found some issues in the current stable. 

1. Performance 
Integrating a lot of logic into the circuit box results in severe performance degradation compared to normal wiring - after just 4 boxes with 50+ components and 80+ wires in each, removing the same amount outside the box - Update ms increased from around 4-5ms to 7-8ms. Using boxes would render some otherwise fine wiring unplayable due to its increased performance impact. (tested in editor and multiplayer / multiple players)

2. Power
It really makes no sense that the Circuit box cannot handle power, as this would be useful for a lot of wiring. It also creates inconsistency as the relay component still have the power input inside. 

3. Corrupt components 
If you mark all components and alter Ability to edit in game check box, it appears to not set the checkbox (and I am unsure whether this feature works) but more importantly some/few components becomes corrupt and must be replaced to gain access to their edit box again. Seems to impact signal and Wifi components. (only tested in editor)

### Reproduction steps

Tested with these files:
Original wiring:
[Riftpiercer X97-S1.zip](https://github.com/FakeFishGames/Barotrauma/files/14450156/Riftpiercer.X97-S1.zip)
With converted to Circuit box wiring:
[Riftpiercer X98-S1.zip](https://github.com/FakeFishGames/Barotrauma/files/14450151/Riftpiercer.X98-S1.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment] 2024-02-29 16:48
Assigned this one to you @3e849f2e5c . Please ask for further information and/or move to QA investigates, if you can't proceed with the current information.

I think the performance issues only have to be addressed if they are severe or if they are trivial to fix. I guess the notion about power might be design-related question. The last point about corrupt components seems like a bug to me.

**Comment by Regalis11** [comment] 2024-03-01 07:06
> I guess the notion about power might be design-related question

In my opinion it's also a feature request, not a bug report. While I agree that it would be useful to pass power through circuit boxes, I think it would complicate the power logic so much that I feel it'd be better to keep things simple and let the circuit boxes be something you only use for signals.

**Comment by Tsunder** [comment] 2024-03-27 00:24
loading this sub in my editor made baro freeze for a minute

**Comment by mygamingaccount** [comment] 2024-04-18 16:42
The Baro editor warns that the number of items on the sub is way more than usual
![sub](https://github.com/FakeFishGames/Barotrauma/assets/68995233/c2c4a837-c1f2-45da-a640-414d30994ec1)

**Comment by Regalis11** [comment] 2024-10-14 14:17
It seems the sub in question is such an extreme case I think it's unfortunately not realistic for us to optimize the system to the point we'd get it to run well. Closing.

**Closed by Regalis11** 2024-10-14 14:17 UTC
Labels: Bug, Feature request, Needs testing, Code, Low prio
