### ISSUE TITLE
TransferAfflictions should transfer relative strength

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13526] opened 2024-03-10 13:20 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

let's say if there's a creature that transforms itself into something else when it's inside the submarine
from original 1000 hp creature to new 1000 hp creature
in this scenario, we do not want crew to deal 1000 damage again if they almost killed the creature outside
this is where TransferAfflictions should work: you dealt 900 damage, so the new creature should have 100 hp left
but that's not the case. In the situation above the new creature will have 910 hp left, because afflictions scale with max hp, which makes TransferAfflictions rather useless if spawned creature has more than 100 health

### Reproduction steps

create similar creature mentioned above and test

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-03-10 15:57
Thank you for the report!

To me it seems like there's some kind of a bug here, and the issue is not that TransferAfflictions should transfer relative strength.

If the monster has let's say 90 internal damage, which results in 900 vitality loss, transferring that 90 internal damage to he new monster as-is should result in 900 vitality loss on the new monster too.

**Comment by kumilanka** [comment] 2024-04-26 13:24
Tested fix to the issue with methods described in the PR ticket. Affliction strength seems to translate correctly now.

**Closed** 2024-04-30 04:02 UTC
Labels: Bug, Code
