### ISSUE TITLE
Fixing ducts in walls is hard for players, impossible for AI

### ISSUE THREAD

**Issue by BlackMoons** [FakeFishGames/Barotrauma#12938] opened 2023-10-29 10:40 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Getting the AI to fix ducts in walls at low height is nearly impossible. It seems you have to be a certain distance away from the wall to interact with it and AI's try to get as close as they can before repairing them, leaving the 'interact' zone.

Tested was a duct (0.75 scale) in a vertical wall (0.5 scale) at foot height.

With the duct at foot height, I couldn't interact with the duct unless I was a few feet from the wall. Chest height works but then it doesn't work very well to drain water. 

Ducts in the floor/ceilings are also kind of hard for AI to repair, as they go to the nearest waypoint and attempt repair, not the waypoint that can actually access the duct from. It can be a per-pixel placement/scale deal getting a duct accessible from one or both sides of a floor without appearing to poke out too far. Ducts that don't poke out of the floor/ceiling seem inaccessible.

Maybe their interaction zone could be made bigger? Or ignore walls blocking their interaction zone. 

### Reproduction steps

Place a duct in a vertical wall with 0 condition, at foot height. 

Tell AI to repair it. the AI will stand there and get stuck, unable to fulfill any other orders. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-11-27 12:42
Potentially related https://github.com/Regalis11/Barotrauma/issues/12649

**Comment by Jasontti** [comment] 2024-01-30 11:33
Could not repro this with ducts or any repairable machines on any height.
Closing ticket

**Closed by Jasontti** 2024-01-30 11:33 UTC
Labels: Bug

**Comment by sqwishy** [comment] 2024-03-04 03:41
Please reopen this issue. It's very easy to reproduce if you follow the detailed report the issue author made for you. You do not need to test any repairable machines on any height, just a duct in the wall at low height. Here is a video reproducing it on unstable.

[footduct.vp9.webm](https://github.com/FakeFishGames/Barotrauma/assets/131432/7b4b58a7-6efe-47e6-84e5-121eab71c2b3)

Here is a copy of the information I provided you on discord.

> There's a check in shared Character.cs:CanInteractWith for Submarine.CheckVisibility between the character and the item's sim positions, for low ducts it reliably hits the wall as you approach the duct. If you offset itemPosition using the rectIntersectionPoint calculated earlier (itemPosition += ConvertUnits.ToSimUnits(rectIntersectionPoint - itemDisplayRect.Center.ToVector2());) then at least the player can fix most ducts provided they are crouching up until they hit repair

Video with that change applied.

[duct.vp9.webm](https://github.com/FakeFishGames/Barotrauma/assets/131432/ded8013f-7bb8-4669-8333-fdd53a95c6fb)

That change is an improvement but isn't perfect; I'm just showing where I think the problem is. If you need more information or help with this, feel free to let me know here or on discord.
