### ISSUE TITLE
resettime for campaign random events doesn't work(when reset it reset monster to "none")

### ISSUE THREAD

**Issue by war3scv** [FakeFishGames/Barotrauma#12131] opened 2023-06-07 09:13 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![6ACL0L58(3@FI )J(@JD{IN](https://github.com/Regalis11/Barotrauma/assets/95470279/5c6bf7bb-31fe-4961-b17d-a45e09cfff95)

this one from the mod I'm making it dosen't work so I go to vanilla ridge kill the latcher, and sat there for 20mins.

![`5 ``O9(}({2QVCJ92%V(3L](https://github.com/Regalis11/Barotrauma/assets/95470279/3957937d-d7e8-4942-8569-a695548e5d32)

and it is the same thing it seem.

### Reproduction steps

go to ridge, kill the latcher, wait 20mins.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2023-06-10 09:45
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1201ac0d344aabaf6b350f010a86f97074855ddb (commit in our private repo)

**Comment by Jasontti** [comment] 2023-07-25 08:22
Tested in campaign.
Still Next event is giving monsters "none"

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/a78946c3-1ec7-4f5f-ba41-4c476f4b4bad)

**Comment by vbnshi** [comment] 2023-08-03 08:40
Tested in campaign.
resettime not work

**Comment by Regalis11** [comment] 2023-08-18 11:08
Could not reproduce. A new abyss monster seems to spawn as soon as the reset timer runs out. You cannot test this by just looking at the event's debug info, because in this case the _event set_ resets, not the event, meaning it'll create a new random event.

@vbnshi The fix is not publicly available yet.

**Comment by Jasontti** [comment] 2023-08-21 10:28
Tested again.
Got second abyss monster spawn after the cooldown.
Closing ticket.

**Comment by war3scv** [comment] 2023-10-31 15:05
is the fix released?

**Comment by Regalis11** [comment] 2023-11-01 06:22
Yep, this fix was included in the Treacherous Tide update.

**Comment by war3scv** [comment] 2023-11-07 10:18
weird it still doesn't work for me, is there any premise for this to work except they all dead?
![20231107180811_1](https://github.com/Regalis11/Barotrauma/assets/95470279/e193ed76-8bd7-41c3-a8ae-5fee8c703cda)

    <EventSet identifier="abyss" chooserandom="true" allowatstart="true" triggereventcooldown="false" resettime="60">
      <MonsterEvent characterfile="Latcher" amount="4" delaybetweenspawns="30" spawntype="abyss" />
      <MonsterEvent characterfile="Charybdis" amount="2" delaybetweenspawns="30" spawntype="abyss" />
      <MonsterEvent characterfile="Endworm" amount="2" delaybetweenspawns="30" spawntype="abyss" />
    </EventSet>

my event is like this. it will be very useful is resettime can work, then I just need spawn one of them at time and mining rich abyss mine will be a mission against the time. also some constant attacks event can be make, so crawler can be a threat without spawn 40 of at same time that lag the hell out of the game.

**Comment by war3scv** [comment] 2023-11-07 11:58
![20231107195604_1](https://github.com/Regalis11/Barotrauma/assets/95470279/cc7a6d8a-4aaa-46cd-9a20-ca3d78109947)

sit at vanilla waste for 3 mins, doesn't seem to work ethier.

    <EventSet identifier="abyss" chooserandom="true" allowatstart="true" triggereventcooldown="false" disableinhuntinggrounds="true" resettime="180">
      <EventSet commonness="10">
        <MonsterEvent characterfile="Latcher" amount="1" spawntype="abyss" />
      </EventSet>
      <EventSet commonness="40">
        <MonsterEvent characterfile="Charybdis" amount="1" spawntype="abyss" />
      </EventSet>
      <EventSet commonness="50">
        <MonsterEvent characterfile="Endworm" amount="1" spawntype="abyss" />
      </EventSet>
    </EventSet>

**Comment by Regalis11** [comment] 2023-11-07 15:01
Thanks for the follow-up! I gave your example XML a test, and in this case the issue seems to be the AllowAtStart setting. The child sets don't seem to inherit that from the parent set, meaning those 3 sets that spawn the monsters aren't allowed at the start of the level, and the game considered you to have travelled 0% of the level when you were in the abyss, and disallowed those events. Adding `allowatstart="true"` to the child sets should fix this, but I'll look into fixing it so that wouldn't be required.

**Comment by war3scv** [comment] 2023-11-07 16:37
that's interesting, I did this but it dosen't work is this the right place to add allowatstart="true"? also it doesn't work for event that doesn't have allowatstart.
      
    <EventSet identifier="abyss" chooserandom="true" allowatstart="true" triggereventcooldown="false" resettime="10">
    	<EventSet allowatstart="true">
      <MonsterEvent characterfile="Latcher" amount="1" spawntype="abyss" />
    </EventSet> 
   </EventSet>

**Comment by Regalis11** [comment] 2023-11-08 08:27
That should be the right place. Could you describe the exact steps you're using to test this? I wonder if I'm doing something differently than you, because I got the monster to respawn with no issues. Looking at your screenshots it seems like the sub might be outside the abyss, in which case the monster should not spawn.

**Comment by war3scv** [comment] 2023-11-08 10:40
I start a new game go down to the abyss kill the latcher sit there for the countdown is this case I set resettime only 10sec for testing purposes then type in debugai when nothing come(either freecam or debugai seem to disable abyss monster spawn entirely if I activate them before I get in to abyss, so I activate them after I sure there nothing come, I think is the freecam). 

I took that vanilla waste screenshot rather late cause initially I didn't saw that event after 3min countdown I thought I was in the wrong biome turns out I'm just rather blind woe for my eyes:(

**Comment by vbnshi** [comment] 2024-01-21 09:30
not fix :(

**Comment by vbnshi** [comment] 2024-01-21 10:38
Tested in campaign.
resettime not work
![1](https://github.com/Regalis11/Barotrauma/assets/95903630/c69104c8-2412-4f63-afc4-97dd30eb25e9)

> 
    <EventSet chooserandom="true" minmissiontime="10" allowatstart="true" triggereventcooldown="false" delaywhencrewaway="false" resetTime="20">
      <EventSet chooserandom="true" allowatstart="true">
        <MonsterEvent characterfile="Punkfish" minamount="4" maxamount="8" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Guppy" minamount="4" maxamount="5" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Seaurchin" minamount="2" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Bombshark" minamount="1" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Europanboxcutter" minamount="2" maxamount="3" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Shroomjelly" minamount="4" maxamount="4" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Europantrout" minamount="2" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Humanhuskold" minamount="1" maxamount="1" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="GoofyFish" minamount="2" maxamount="10" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="RedFish" minamount="2" maxamount="10" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Thrasher" minamount="4" maxamount="6" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Hornshrimp" minamount="1" maxamount="1" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Icecrab" minamount="1" maxamount="2" scatter="3000" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Spineling" minamount="1" maxamount="2" scatter="3000" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Icedleatherback" minamount="1" maxamount="1" scatter="3000" spawntype="mainpath,sidepath" />
        <MonsterEvent characterfile="Hammerhead_maneater" minamount="1" maxamount="1" scatter="3000" spawntype="mainpath,sidepath" />
      </EventSet>
    </EventSet>
 

or

> 
    <EventSet chooserandom="true" minmissiontime="10" allowatstart="true" triggereventcooldown="false" delaywhencrewaway="false" resetTime="20">
        <MonsterEvent characterfile="Punkfish" minamount="4" maxamount="8" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Guppy" minamount="4" maxamount="5" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Seaurchin" minamount="2" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Bombshark" minamount="1" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Europanboxcutter" minamount="2" maxamount="3" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Shroomjelly" minamount="4" maxamount="4" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Europantrout" minamount="2" maxamount="2" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Humanhuskold" minamount="1" maxamount="1" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="GoofyFish" minamount="2" maxamount="10" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="RedFish" minamount="2" maxamount="10" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Thrasher" minamount="4" maxamount="6" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Hornshrimp" minamount="1" maxamount="1" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Icecrab" minamount="1" maxamount="2" scatter="3000" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Spineling" minamount="1" maxamount="2" scatter="3000" spawntype="mainpath,sidepath" delaybetweenspawns="1" />
        <MonsterEvent characterfile="Icedleatherback" minamount="1" maxamount="1" scatter="3000" spawntype="mainpath,sidepath" />
        <MonsterEvent characterfile="Hammerhead_maneater" minamount="1" maxamount="1" scatter="3000" spawntype="mainpath,sidepath" />
    </EventSet>
 

Whether allowatstart="true" is added or not,
resetTime won't even work

**Comment by Regalis11** [comment] 2024-01-21 12:41
We've implemented a fix for this (https://github.com/Regalis11/Barotrauma-development/pull/4631), but it's unfortunately not yet available in the public version of the game. Sorry for the inconvenience!

**Comment by itchyOwl** [comment] 2024-02-05 09:20
Confirmed to be fixed in FakeFishGames/Barotrauma-development#4631.

**Closed by itchyOwl** 2024-02-05 09:20 UTC
Labels: Bug, Code
