### ISSUE TITLE
Bad performance in large outposts and colonies or after swarm of enemies spawn on a mission

### ISSUE THREAD

**Issue by Feanor1397** [FakeFishGames/Barotrauma#13160] opened 2023-12-14 15:11 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I experience huge performance drops in large outposts and colonies. Similar happens when large swarm of enemies spawn ie when I return from abyss to main floor of level. In the latter case performance returns to normal the moment I kill all the enemies. In both situations I see large numbers in showperf for physics and SolveUpdateTime

This screenshot is for military outpost. Numbers sit around 8-10 (ms I guess?). In Colonies this can go up to 14 for physics and 12 for SolveUpdateTime
![Screenshot_20231214_181058](https://github.com/Regalis11/Barotrauma/assets/20919503/d333211e-36a5-4418-be3f-db8b74aa9106)

This happens on both 1.1.19 and latest from unstable. Previous time I played right before 1.x release and didn't experienced this (except for colonies but not so drastically).

### Reproduction steps

Dock to colony or spawn 10-15 spinelings or threshers

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by Feanor1397** [comment] 2023-12-14 15:28
Little update. I have killed every NPC on a station and this helped.
![Screenshot_20231214_192527](https://github.com/Regalis11/Barotrauma/assets/20919503/1b8f4b1f-73c3-40dc-bf76-b6bd8c545727)

**Comment by Regalis11** [comment] 2024-02-13 11:25
There have been some improvements to this in the latest patches, but the issue is still not fully resolved. We have an existing ticket about [general performance issues](https://github.com/FakeFishGames/Barotrauma/issues/9396), which partially overlaps with this one, so I'll close this as a duplicate.

**Closed by Regalis11** 2024-02-13 11:25 UTC
