### ISSUE TITLE
[Unstable] Outposts can no longer be assigned factions

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13474] opened 2024-02-23 19:38 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Worked in previous unstable but it broke

`ad86d3f676: Option to force location types to be owned by a specific faction. Necessary for modders (makes it possible to create let's say locations belonging to the husk cult, without having to make the husk cult a part of the random outpost assignment and create a ton of modules to support turning any outpost into a cultist outpost).` Regalis11/Barotrauma#12790

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/e04b58c1-1f8b-42a0-a225-5dcb6183d0a0)

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/4b338eaf-8713-43ca-964a-f6dd58a1d2dc)

### Version

v1.2.12.0 (unstable)

**Comment by Regalis11** [comment] 2024-02-24 09:04
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/12790. The feature hasn't been merged yet, we just included in the "very unstable unstable build" in December along with a bunch of other untested and unmerged features.

**Closed by Regalis11** 2024-02-24 09:04 UTC
