### ISSUE TITLE
DelayedEffect with delaytype="ReachCursor" is always applied immediately, regardless of whether the projectile reaches the cursor or not

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13429] opened 2024-02-14 08:33 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When you specify the DelayType of DelayedEffect as ReachCursor, before the Effect is applied, it will calculate the distance from the item to the Cursor position of its projectile.User. If the displacement of the projectile exceeds this distance, the Effect will be applied.
But now, as the title says, the displacement has exceeded the predetermined distance before Effect is applied.

### Reproduction steps

1. Copy the following xml code into any projectile component of any item:
```xml
<StatusEffect type="OnUse" target="This" delaytype="ReachCursor">
    <Remove />
</StatusEffect>
```
2. Shoot the modified projectile
3. projectile will be removed immediately

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-02-14 10:16
The predetermined distance in this case seems to be 0 (as you have not defined any distance), so the expected behavior is that the effect triggers immediately (since the distance will always be larger than 0).

**Comment by zhu-rengong** [comment] 2024-02-14 12:39
Actually we don't need to give the distance, because distance = Vector2.Distance(projectile.WorldPosition,character.CursorWorldPosition), it depends on where your cursor position is.

**Comment by Regalis11** [comment] 2024-02-19 09:14
Ah, you're right, I'd missed that part of the code!

Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/c9d49ed77e5cfdc54a82c60b140b5002736a403d

**Comment by Regalis11** [comment] 2024-09-11 07:56
Merged, closing

**Closed by Regalis11** 2024-09-11 07:56 UTC
Labels: Bug, Code, Modding
