### ISSUE TITLE
Players get through walls at left lower corner of Azimuth

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13348] opened 2024-01-25 06:19 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/FakeFishGames/Barotrauma/assets/64390906/ebf31fb7-43e9-45a8-bf93-2be45551aa18

### Reproduction steps

1. go to submarine editor
2. select Azimuth then test

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-25 07:33
Seems to be caused by https://github.com/FakeFishGames/Barotrauma/issues/13240, should be addressed by https://github.com/FakeFishGames/Barotrauma-development/pull/4804 (PR in our private repo)

**Comment by Rokvach** [comment] 2024-01-25 12:18
Tested, working correctly. Can be merged and closed.

**Closed** 2024-01-25 12:26 UTC
Labels: Bug
