### ISSUE TITLE
StatusEffectAction fails to play a sound when the first time it is triggered in multiplayer

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13406] opened 2024-02-08 06:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

in multiplayer, first StatusEffectAction within a custom ScriptedEvent does not play sound at all
it works fine in singleplayer mode

### Reproduction steps

1. use following ScriptedEvent
```
<ScriptedEvent identifier="hauntingvent">
  <TagAction criteria="player" tag="player" />
  <TagAction criteria="itemidentifier:vent" tag="potentialvent" submarinetype="player" />
  <TriggerAction target1tag="player" target2tag="potentialvent" applytotarget1="triggerer_player" applytotarget2="selectedvent" radius="100" waitforinteraction="false" />
  <StatusEffectAction targettag="selectedvent">
    <StatusEffect>
      <Sound file="Content/Sounds/Damage/GlassImpact3.ogg" range="10000" dontmuffle="true" Volume="1.5" />
    </StatusEffect>
  </StatusEffectAction>
  <SpawnAction speciesname="Crawler_hatchling" targettag="crawler" spawnlocation="MainSub" spawnpointtag="selectedvent" />
</ScriptedEvent>
```
2. enter singleplayer campaign mode
3. use console command "triggerevent hauntingvent" to trigger the event
4. approach a vent in player's submarine
5. the sound is properly played and a crawler hatching spawns
6. do the same steps above but in multiplayer
7. the sound does not play at all

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-02-13 08:57
Most likely caused by the same issue as https://github.com/FakeFishGames/Barotrauma/issues/12995, should be fixed in the latest unstable build.

**Comment by Regalis11** [comment] 2024-06-18 12:41
Does not seem to be fixed after all, got a more recent report about this https://github.com/FakeFishGames/Barotrauma/discussions/14009

**Comment by Regalis11** [comment] 2024-06-18 15:14
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5482/commits/7d057cd3794cbfed41f40d3a5b50b416a19935cd

**Comment by Jasontti** [comment] 2024-06-25 13:46
Tested in: https://github.com/FakeFishGames/Barotrauma-development/commit/41364a7aa39bf32a7d49e604ad9a5377f4dbcf41

Tested in SP and MP
Tested with example provided and other naturally occuring events

No issues found

**Closed by Jasontti** 2024-06-25 13:46 UTC
Labels: Bug, Code
