### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by AceCranel7** [FakeFishGames/Barotrauma#13347] opened 2024-01-25 06:06 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While reaching the next station the game crashed, (was navigating the sub)

### Reproduction steps

1. Start a single player campaign
2. Play the game like the usual
3. While reaching the 2 station the game crashed

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/25/2024 14:02:34)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

The crash was caused by the DirectX error DeviceRemoved (HRESULT = 0x887A0005). This is a common DirectX error that can be related to various different issues, such as outdated drivers, RAM problems or an overclocked or otherwise overstressed GPU. There are several potential ways to fix the issue: ensuring your graphics drivers and DirectX installation are up-to-date, disabling overclocking and adjusting various GPU-specific settings. You may also be able to find potential solutions to the problem by using the error code DeviceRemoved (HRESULT = 0x887A0005) and your GPU manufacturer as search terms.

77D218D1871FDDD4464482493DDFEE17

Game version 1.2.8.0 (ReleaseWindows, branch release/winter-update-hotfix-2, revision b9f79cb182)
Graphics mode: 1366x768 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla (F748F32), Dianna-2 (FF638F2), FDF-Eternity-2 (58741AC), FDF-Vortex 1 (EAA1984), Ixion-2 (0B8932A), Rastoc (E38D076), Silver Fury (B8E4DF2), KM 42 Das Mädchen (9D19466), NEX-宿怨-级攻击舰 (67471AF), Wreck Locator (CFABD6F), FDF-Vulture (7E773EA), Alicorn2 Stealth Light Cruiser (8FEFA8D), Dont Open Debug Console On Errors (59B0D91), FDF-Chopper Shuttle (C61075E), FDF-Vortex (887F9E8), Cruel Accordion (09EF0D6), Basilisk Battlecruiser (70822EC), Copperhead (1736E22), Minotaur (BFC1CC9), Argo (11AEF11), Mechno's and Duke's Maddened Black Sea Armory (07B7A7A), Shreksophone-Reloaded (4F76329), The Drunken Sailor (B3EC310), Hydroponics (0832911), Dugong Ultimate (C84DD3B), FDF-Eternity (4ECBC96), Dianna (FA44C04), “Silver Fury” Class Scout Submarine (4038D7B), THG Armory - 'Vanilla' Turret pack (739C70A), Saber Personal Protection Remake Rework (ABB3D4D), Saber Armaments Revived (564FBE4), DA-Maelstrom (Remade) (8C8840B), Ixion (2BEA8AE), Omega Energy Weapons (BD409E3), Rastoc (D35EB9D), Trigger-1 (8E42D76), Mule (T1 Transport) (32B4B2B), Trigger-2 (639832C)
Level seed: LocationName.generic.5118LocationName.city.6025
Loaded submarine: Trigger-2 (4D6144C7CD4BF9CEB43FD9582D03E4AE)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
 (SharpDX.SharpDXException)
Device removed reason: DeviceRemoved (HRESULT = 0x887A0005)
Target site: Void PlatformPresent()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/25/2024 14:02:34] Level identifier: coldcavernsbasic
[01/25/2024 14:02:16] Transitioning to LocationName.generic.5118LocationName.city.6025 (current location: Xinzou Outpost, selected location: Jokull Habitation Outpost, leaving sub: Trigger-2, at start: True, at end: False, transition type: LeaveLocation)
[01/25/2024 14:01:39] Unlocked mission "Arms Delivery" in the connection from "Xinzou Outpost" to "Jokull Habitation Outpost".
[01/25/2024 14:01:36] Unlocked mission "Killing a large crawler" in the connection from "Xinzou Outpost" to "Jokull Habitation Outpost".
[01/25/2024 14:01:34] Unlocked mission "Mining Quartz" in the connection from "Xinzou Outpost" to "Vorta Outpost".
[01/25/2024 13:59:50] Generating an outpost for the start of the level... (Location: Xinzou Outpost, level type: Outpost)
[01/25/2024 13:59:50] Level identifier: outpostlevel
[01/25/2024 13:59:32] Transitioning to LocationName.city.6025 (current location: Apep Outpost, selected location: Xinzou Outpost, leaving sub: Trigger-2, at start: False, at end: True, transition type: ProgressToNextLocation)
[01/25/2024 13:52:39] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: LocationConnection)
[01/25/2024 13:52:37] Generating an outpost for the end of the level... (Location: Xinzou Outpost, level type: LocationConnection)
[01/25/2024 13:52:37] Level identifier: coldcavernsbasic
[01/25/2024 13:52:19] Transitioning to LocationName.city.6025LocationName.city.353 (current location: Apep Outpost, selected location: Xinzou Outpost, leaving sub: Trigger-2, at start: True, at end: False, transition type: LeaveLocation)
[01/25/2024 13:49:22] Unlocked mission "Mining Quartz" in the connection from "Apep Outpost" to "Xinzou Outpost".
[01/25/2024 13:49:20] Unlocked mission "Killing a large crawler" in the connection from "Apep Outpost" to "Xinzou Outpost".
[01/25/2024 13:49:17] Unlocked mission "Medical item transport" in the connection from "Apep Outpost" to "Xinzou Outpost".
[01/25/2024 13:48:28] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/Chaingun/chaingun round.png, size: 36x9)
[01/25/2024 13:44:40] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: Outpost)
[01/25/2024 13:44:40] Level identifier: outpostlevel
[01/25/2024 13:25:00] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:21:27] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:19:13] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:16:34] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:15:45] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:13:47] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Content/Items/Legacy/legacyrailgunbarrel.png, size: 125x336)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Hydroponics]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2949539738/Hydroponics/EngiHat.png, size: 87x47)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Saber Personal Protection Remake Rework]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3049032587/Saber/hedwba.png, size: 85x79)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Saber Personal Protection Remake Rework]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3049032587/Saber/hedwbb.png, size: 85x79)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/BT/BT.png, size: 140x102)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Saber Personal Protection Remake Rework]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3049032587/Saber/armoricons.png, size: 416x133)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Saber Personal Protection Remake Rework]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3049032587/Saber/poweredheadgears.png, size: 645x881)
[01/25/2024 13:13:26] ‖color:#9370DB‖[Saber Personal Protection Remake Rework]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3049032587/Saber/hedba.png, size: 86x82)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/PRG/PRG.png, size: 280x125)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/Chaingun/chain gun ammo box.png, size: 95x70)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/LMG/lmg mag.png, size: 35x45)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/BT/RG.png, size: 280x125)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/Chaingun/14.5 ammo box.png, size: 95x70)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/LMG/lmg mag2.png, size: 35x45)
[01/25/2024 13:13:24] ‖color:#9370DB‖[Mechno's and Duke's Maddened Black Sea Armory]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891792017/PRG/shell.png, size: 65x16)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/proxydecoynukecharge.png, size: 129x85)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/proxydepthcharge.png, size: 129x85)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/fragbox2.png, size: 83x59)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/turretbase.png, size: 222x222)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/proxynukecharge.png, size: 129x85)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/fragbox.png, size: 83x59)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/fragbox3.png, size: 83x59)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/fragloader.png, size: 162x354)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/proxydecoycharge.png, size: 129x85)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/explosivepulselaser.png, size: 97x80)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/explosivechaingun.png, size: 95x78)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/depthchargemortarloader.png, size: 170x352)
[01/25/2024 13:13:21] ‖color:#9370DB‖[THG Armory - 'Vanilla' Turret pack]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/UserPC/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3036314567/thoriumpulselaser.png, size: 97x80)
[01/25/2024 13:10:23] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[01/25/2024 13:10:20] Logged in as Kranel Deugruchaffe (SteamID STEAM_1:0:496078077)
```

**Comment by AceCranel7** [comment] 2024-01-25 06:12
Oh wait, nvm found an old post from 2022 with the same issue

**Comment by AceCranel7** [comment] 2024-01-25 06:15
Weird, all is good on my end
1. Drivers updated
2. Rams are a-okay
3. I don't know what to do.

**Comment by Regalis11** [comment] 2024-01-25 07:24
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/10540

**Closed by Regalis11** 2024-01-25 07:24 UTC
