### ISSUE TITLE
[Modded] Door state isnt synced with physical door position when held force open

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#13068] opened 2023-11-20 17:50 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

it seems like when door held open via conditionals - it desyncs with signal door state (and it also instantly sets door to open instead of opening it as if player clicked it)

You can clearly hear it opening and closing meanwhile physically it stays open as well as observe door not closing instantly after I click button (Because it is assume to be closed, so I had to click it 1 more time)

https://github.com/Regalis11/Barotrauma/assets/42521948/b20ee812-34ba-4e0e-a66d-9c25acf52da7

### Reproduction steps

1. Download [FNaF Doors.zip](https://github.com/Regalis11/Barotrauma/files/13417958/FNaF.Doors.zip) and put it in your LocalMods
2. Load up submarine `Azimuth_Door_Test` 
3. Repeat same actions as on video

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment] 2024-01-04 09:45
Thank you for the report!

To me this doesn't actually seem like a bug. The IsOpen property doesn't control whether the door should open or close, but whether it _is_ currently open or closed. If you set it via status effects, the door will appear to fully close/open immediately.

> You can clearly hear it opening and closing meanwhile physically it stays open

This also seems like the expected behavior to me. The status effect is forcing the door to always stay open, so you won't have any time to see the door starting to close because it gets immediately re-opened.

I suppose we could add a property that allows opening or closing the door without setting the state immediately.

**Comment by Regalis11** [comment] 2024-01-04 09:49
Added a property called `ShouldBeOpen` in https://github.com/Regalis11/Barotrauma-development/commit/9c4dad116c16d8684ddc2d93426fe53105f50049

**Comment by PanmanS** [comment] 2024-01-04 12:12
Thanks!

**Comment by Jasontti** [comment] 2024-05-20 12:30
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4820/commits/04eefbdbf515ae30a069b0abfccc46521890142b

Used the test mod provided and modified the statuseffect to have ShoulBeOpen instead of IsOpen
Door behaves more realistically, statuseffect forces it back open when closed
Noting that door does quiver a bit when it gets conflicting orders
Tested normal door operation with vanilla subs

No issues found
Closing ticket as completed

**Closed by Jasontti** 2024-05-20 12:30 UTC
Labels: Feature request, Code, Modding
