### ISSUE TITLE
[Unstable] Medic Bot attempting to cure Infection affliction causes crash to desktop

### ISSUE THREAD

**Issue by bookslayer10** [FakeFishGames/Barotrauma#13414] opened 2024-02-10 03:04 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When an NPC tries to apply medicine to something else, the lobby will often crash to desktop.

### Reproduction steps

1. Start a multiplayer lobby with medic bots present
2. Take away all medical supplies used to treat infection
3. apply infection by using giveaffliction Infection 30 [any crewmember name]
4. Instruct medic bots to heal injury, they can't find the medicine, nothing happens
5. Spawn in broad spectrum antibiotics for the bots
6. A few seconds after the medics start applying medicine, the game crashes

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.10.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

The server has crashed: servercrashreport (21).log||
Value cannot be null. (Parameter 'key') (ArgumentNullException)    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Barotrauma.CharacterHealth.GetAfflictionLimb(Affliction affliction) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 372
   at Barotrauma.AIObjectiveRescue.ApplyTreatment(Affliction affliction, Item item) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveRescue.cs:line 474
   at Barotrauma.AIObjectiveRescue.GiveTreatment(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveRescue.cs:line 328
   at Barotrauma.AIObjectiveRescue.Act(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveRescue.cs:line 65
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 180
   at Barotrauma.HumanAIController.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 478
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3148
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 188
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 319
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 79

**Comment by Regalis11** [comment] 2024-02-11 10:23
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13355

**Closed by Regalis11** 2024-02-11 10:23 UTC
