### ISSUE TITLE
Bots getting stuck on some ladders in submarines

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13744] opened 2024-04-08 06:37 UTC
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13600

<div type='discussions-op-text'>

<sup>Originally posted by **Exoteklas** March 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On 2 occasions in submarines I have experienced that there are places where bots get trapped in stairs trying to go to a task, repair, fill air tanks, etc. It has happened to me with the submarine "Camel" and the "typhon 1" simply The characters are trapped there without being able to do anything until I control them manually, this can be a bit annoying when playing alone since, for example, if the engine in "typhon" is damaged, the bots cannot reach it and I have to move them to get there let them fix it, I will attach a photo of where they are stuck and also a video as proof, also a photo of the version of the game and just to be clear, the game is not pirated, it is purchased on steam

https://github.com/FakeFishGames/Barotrauma/assets/163709678/5f3ae06d-e69c-430d-88a8-ef94d8f11f60

![image](https://github.com/FakeFishGames/Barotrauma/assets/163709678/321029f9-d2a7-4525-8dbe-1d1f7949f7a0)
![VERSION](https://github.com/FakeFishGames/Barotrauma/assets/163709678/0a2e3d26-b753-4041-9494-3539fdbdade4)

### Reproduction steps

just add as a task, repair cracks, engine or fill oxygen cans in typhon

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment] 2024-04-10 10:13
Wasn't able to repro this in Typhon. Tried to make a bot follow me, clean up items (dropped some items around), fix leaks (caused some leaks), and the bot was able to path through the ladders just ok. Needs better steps to repro.

**Comment by NotWendy** [comment] 2024-04-11 10:59
May be related to this:
https://github.com/FakeFishGames/Barotrauma/discussions/13598

**Comment by michael-fakefish** [comment] 2024-11-27 10:09
Could not reproduce in Typhon by:
-Making bots to follow on ladders
-Making bots to clean up items
-Making bots to deconstruct items while approaching from the ladder above
-Making bots repair leaks in locations accessible by ladders only

Using the submarine editor and moving e.g. the deconstructor or nuclear reactor closer to the ladder, as described in #13598 , and giving a bot an order to operate them while approaching from above using the ladder got the bots stuck, but any changes to the submarine aren't visible in the original video.

**Comment by itchyOwl** [comment] 2024-12-05 09:27
The issue mentioned above should be fixed in FakeFishGames/Barotrauma-development@8eae841. I'm not 100% sure it's the same one, but since we can't repro the original case here, let's assume it is.

**Comment by Regalis11** [comment] 2024-12-17 08:07
Merged, closing

**Closed by Regalis11** 2024-12-17 08:07 UTC
Labels: Bug, Code, Ticket
