### ISSUE TITLE
AND component sometimes outputs incorrectly 

### ISSUE THREAD

**Issue by Tsunder** [FakeFishGames/Barotrauma#8668] opened 2022-03-31 02:45 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AND component should output true if there's a(t least one) non-zero signal in BOTH inputs

however, it is apparently possible to wire a circuit that sends a 1 into both signals but the AND outputs false, due to a 0 being inputted as well.

**Steps To Reproduce**
Item assembly containing faulty AND:

[test (1).zip](https://github.com/Regalis11/Barotrauma/files/8385499/test.1.zip)

Recreating the circuit by my hand didn't yield the same results, IMO potentially due to update order stuff.

**Version**
0.16.something stable

**Additional information**
#5001

**Comment by Regalis11** [comment] 2022-03-31 14:03
I'm afraid I couldn't find any issues with this circuit. By default, the and component outputs true, and when I click the button, it starts sending out false.

Looking at the code, I can't think of how the 0 signals could interfere with the and component:
https://github.com/Regalis11/Barotrauma-development/blob/aa4c852c2c333438ac54823601525072558da518/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/AndComponent.cs#L105

**Comment by Regalis11** [comment] 2022-03-31 14:06
Also a potential duplicate of https://github.com/Regalis11/Barotrauma/issues/6501

**Comment by Regalis11** [comment] 2022-04-01 10:31
Ah, I misunderstood the issue then. Thanks for the clarification, I'll take another look!

**Comment by mygamingaccount** [comment] 2023-12-17 17:41
Don't know what caused the issue, but it no longer happens.

In @Tsunder's circuit the AND outputs only ones.

**Comment by itchyOwl** [comment] 2024-09-25 07:47
Possibly resolved. Moving to candidates for removal.

**Closed** 2024-11-15 07:48 UTC
Labels: Bug, Needs testing, Code
