### ISSUE TITLE
docked submarines barely has buoyancy physics

### ISSUE THREAD

**Issue by Tsunder** [FakeFishGames/Barotrauma#5974] opened 2021-06-05 04:51 UTC
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having a docked, flooded shuttle affects the buoyancy of the larger ship less than expected.
expected is that the ship will sink as fast as if an equivalent additional hull on the main ship was added and flooded.

**Steps To Reproduce**
1. flood a shuttle with a hull volume that would be noticable in main sub's ballast, for example as much volume as the main sub would need to be neutral in water

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
ship with a flooded hull, just barely big enough to be sinking (0.994 NBL) - performs as expected, a slow descend
![image](https://user-images.githubusercontent.com/5103517/120880251-2ebffe00-c597-11eb-940a-6cb1163b5756.png)

vs same hull but put as a Shuttle - sub ascends at nearly full speed
![image](https://user-images.githubusercontent.com/5103517/120880232-03d5aa00-c597-11eb-8519-4f4a2451ade3.png)

4x NB worth's of shuttle volume - still slightly ascending. Somewhere between 4x and 5x in shuttle volume is required to hit neutral.
![image](https://user-images.githubusercontent.com/5103517/120880311-cb829b80-c597-11eb-8a2a-35840ae19575.png)

**Comment by Orum** [comment] 2023-02-04 02:16
Is this ever going to be fixed?  I've noticed a related issue where the NBL my sub *should* have (based on hull and ballast volumes) is incorrect.  The symptoms are slightly different because I'm not trying to flood the docked sub while leaving the main one empty, and the docked "drone" is much larger than my main sub.

The issue manifests itself as a fair amount of missing hull volume.  Here's a spreadsheet I made to calculate everything:
![NBL](https://user-images.githubusercontent.com/547467/216741182-eabfa0cf-8fd4-48ca-b213-3f6a81b6a3a7.png)

The "empirically derived" value was from setting my sub in hold position.  As you can see, it's 'missing' about 44,000 hull value, compared to what is stated in the editor!

**Comment by Orum** [comment] 2023-04-02 06:27
After doing a lot more research into this (to make a dynamically adjusted NBL possible), I can say with certainty that this is not as simple as just adding additional hull volume, as I previously thought.

In fact, I can't even figure out exactly what bug is in the code based on empirical testing.  For my subs that use a dynamic NBL I ended up just doing a linear regression based on the data, but even this has more error than I'd like.  More complex regressions simply aren't worth implementing, at least in part due to the limited amount of mathematical tools we're provided.

**Comment by Regalis11** [comment] 2023-04-26 07:27
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/88d2338365745f5bc18ea4908ff439b1c267e3ac

**Comment by Jasontti** [comment] 2023-07-10 07:05
Tested.
Subs are properly sensitive to other docked subs or shuttles.
No issues found with engine throttle or buoyancy.
Closing ticket.

**Comment by Regalis11** [comment] 2023-12-20 08:35
Does not seem to be fully fixed, reopening https://github.com/Regalis11/Barotrauma/issues/13200

**Comment by Jasontti** [comment] 2024-01-24 12:20
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4789/commits/79cd152f6184e88d0211ae0ea96cd0efae60abff

Created dugong with docked ballast and compared it to stock dugongs performance
Stock dugong managed -19 to 12 in descent velocity
Modified did ship matched this

![image](https://github.com/FakeFishGames/Barotrauma/assets/8488224/9ec88517-a048-4f68-ab4d-340f315f9a6f)

Tested Kastrull and other vanilla subs also

No issues found
Closing ticket

**Closed by Jasontti** 2024-01-24 12:20 UTC
Labels: Bug, Code
