### ISSUE TITLE
[Sub Editor][English] Hull Name Presets Missing

### ISSUE THREAD

**Issue by VaelophisNyx** [FakeFishGames/Barotrauma#13492] opened 2024-02-27 01:45 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Apparently there's a bug in the sub designer causing the presets for hull object names to just not load for the english language localization
if you switch to any other they show up correctly

Additionally if manually typed into the hull name, they show correctly in game. Only the list appears broken.
They, additionally, do still exist in EnglishVanilla.XML. It seems to just be a loading issue for specificlaly english

### Reproduction steps

1. Switch to English localization
2. Open the sub editor
3. select or place a hull object
4. attempt to select a preset
5. the list is blank
6. switch to any other language
7. the list is not blank

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub Editor; no effect in gameplay

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment] 2024-02-27 01:49
English:
![image](https://github.com/FakeFishGames/Barotrauma/assets/1534478/4edbaee3-199e-4ed8-ba16-889477c86cc0)

German:
![image](https://github.com/FakeFishGames/Barotrauma/assets/1534478/b4ac99a5-d3fd-434f-87fe-a167c19a0190)

just for a quick visual example. There was no reload between these, just a swap to German from English, and reopening the presets menu.

**Comment by Regalis11** [comment] 2024-02-27 07:54
I'm afraid I could not find a way to reproduce this. To be sure, you don't have any mods enabled? The issue above causes the list to be empty if a mod overrides any texts, but if you're not using any mods, I'm not sure how to get this to occur. :/

**Comment by VaelophisNyx** [comment] 2024-02-27 10:02
While I do have a handful of mods (mostly LUA stuff), this does seem to happen with vanilla users too, according to at least 1 steam discussion from last month; thus the mods disclaimer being unchecked.
I'm not even sure what mod _could_ cause this kind of issue, especially for just one language

**Comment by VaelophisNyx** [comment] 2024-02-27 10:15
Upon some digging, I've found the mod at fault in my case seeing as that bug exists (Improved Stun)
As for why it'd make it only broken for english, it turns out it only has english and russian language files, so none of the other languages provided by the game are effected.

**Comment by Regalis11** [comment] 2024-02-27 10:23
Thanks for the extra info! In that case it seems like this is a duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13340. We've got a fix up in the unstable branch, which will be included in the next update. Sorry for the inconvenience!

**Closed by Regalis11** 2024-02-27 10:23 UTC
Labels: Bug, Need more info

**Comment by VaelophisNyx** [comment] 2024-02-27 10:27
a recommendation I'd have btw is some sort of maintained Known Issues thread either here or on steam's discussion forum. May be a lot to maintain but would also cut down on duplicates a bit more than blind searching does!

**Comment by Regalis11** [comment] 2024-03-14 07:37
Well, considering the number of known issues, (about 300 atm), I feel like maintaining one would be like maintaining two copies of the issue tracker. 😅
