### ISSUE TITLE
Logbook didn't spawn inside wreck for "Wreck Salvage" mission

### ISSUE THREAD

**Issue by Mabons** [FakeFishGames/Barotrauma#13265] opened 2024-01-05 10:57 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Selected Wreck Salvage mission, found the wreck by happen chance thinking it was an additional wreck, searched it completely (not a lot of openable cabinets) and found no logbook. Then followed "Wreck" marker on sonar, it took us about 500m past and below the end of the instance, marker lead us to open water no sign of anything else.

### Reproduction steps

Seed: SlqDRkhi
This happened by getting Wreck mission from Moyle Cavus Mines in the European Ridge, and travelling to Mandel Wastes Mining Facility.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment] 2024-02-14 08:01
Cannot reproduce this. I've tried both a campaign save with the seed as well as mission mode with the seed SlqDRkhi on a server (with multiple attempts and difficulty ranges), both did not show any issues with the salvage mission.

If you (or anyone else) encounter this again, a save file of that campaign would be nice for reproducing the issue. Even if the campaign has since past that point it may still be helpful.

**Comment by Regalis11** [comment] 2024-03-01 11:07
No known steps to repro, closing

**Closed by Regalis11** 2024-03-01 11:07 UTC
Labels: Need more info
