### ISSUE TITLE
Linked submarine (shuttle, railgun rack) not moving up and down after undocking

### ISSUE THREAD

**Issue by Minedeployder** [FakeFishGames/Barotrauma#13182] opened 2023-12-16 22:23 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Sup. 1.2 update break some hatches (that is attached as shuttles) and some modern subs are malfunction. When you press undock button, it just goes 10cm up and thats it. Can you guys please fix it? 

For example: 
Hatch and walls for armory
https://steamcommunity.com/sharedfiles/filedetails/?id=2445826783&searchtext=lyra

Railgun loader mechanism
https://steamcommunity.com/sharedfiles/filedetails/?id=2947218169

Hatch
https://steamcommunity.com/sharedfiles/filedetails/?id=2888671244 

### Reproduction steps

1. Select any of custom subs
2. Find and push lever
3. Use freecam to see hatch is stuck.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Minedeployder** [comment] 2023-12-20 14:15
In Lyra it is in shuttle. Hatch has to go down and go to right.
In patchwork railgun rack just should go down or up. In all cases now it undocks and just stuck

**Comment by Minedeployder** [comment] 2023-12-20 14:19
Upd. In Lyra hatches controls hidden at nose(as i remember), but if go with easier option, in Patchwork it is in the middle of ship(in water), there are half-transparent components

**Comment by Regalis11** [comment] 2023-12-20 14:37
Thanks for the clarification! What should be moving the linked submarine? I cannot see any obvious mechanisms that could be moving them.

**Comment by Minedeployder** [comment] 2023-12-20 14:40
https://steamcommunity.com/sharedfiles/filedetails/?id=2947218169

Demonstraion on gif (pic.4)

**Comment by Regalis11** [comment] 2023-12-20 14:42
I understand the rack is supposed to move up and down, but how? What is moving it?

**Comment by Minedeployder** [comment] 2023-12-20 15:02
small pump in small hull, that is attached to docking port

**Comment by Minedeployder** [comment] 2023-12-20 15:22
If you want to see how the rack look itself, you can use this tool (not sure if there other way)
https://ignis05.github.io/baro-save-editor/SubTools

Upload sub file, download "r", (not remembmer name of rack, but it is not I II or III) so you can open it in game.

**Comment by Minedeployder** [comment] 2023-12-24 16:35
Since it will take way too much time, it is up to Lyra.
I already reworked "patchwork" railgun rack with completely different mechanism, and it will took me some extra days to replace it in Humpback, but lyra probably never be updated again.

Those are the mechanism that is not working.
![загружено](https://github.com/Regalis11/Barotrauma/assets/70541484/9420ef89-e48f-4b72-b410-e3a16be9d1a5)

**Comment by Minedeployder** [comment] 2023-12-25 22:18
I found the issue. 1.2 broke some objects placements. Smalls pumps, railguns, engine, and so on just got randomly offset.
Red how it should be, yellow how it is past 1.2
![4](https://github.com/Regalis11/Barotrauma/assets/70541484/a05d132e-2619-4c50-98b0-6d2fa36d2e2f)

**Comment by Minedeployder** [comment] 2023-12-25 22:18
Or this. How it should look vs how it is look like. Pump just cant even touch the hull

![Barotrauma Screenshot 2023 12 25 - 23 49 21 87](https://github.com/Regalis11/Barotrauma/assets/70541484/ee3cff95-7468-4034-816b-5d2c8d65eb37)
![Barotrauma Screenshot 2023 12 25 - 23 49 30 12](https://github.com/Regalis11/Barotrauma/assets/70541484/bf40dfcd-7e62-44e6-bd41-75e99490a62a)

**Comment by Minedeployder** [comment] 2023-12-25 22:25
btw as you see it happened only to small shuttles

**Comment by Regalis11** [comment] 2023-12-26 15:35
I'm glad you found the issue! We still need to look into why the devices are getting offset like this though, but that will take a while longer because we're currently on our Christmas holidays. Sorry for the inconvenience!

**Comment by Regalis11** [comment] 2024-03-06 16:04
Seems to be a duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13110, closing

**Closed by Regalis11** 2024-03-06 16:04 UTC
Labels: Bug, Need more info, Modding
