### ISSUE TITLE
Machinegun Spinelings

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#12384] opened 2023-07-20 11:14 UTC
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Given the proper angle or pattern, Spinelings can shoot up to to 3 times per second and kill you very fast

Attacks have `secondarycooldown="0.3"` 

https://github.com/Regalis11/Barotrauma/assets/73229309/724401dd-b197-4c79-82a3-d38ad49750db

### Reproduction steps

Be unlucky/too close to a spineling

### Version

v1.0.21.0

**Comment by G-M-twostay** [comment] 2023-07-21 02:23
at first sight i thought u were suggesting machine gun spineline.

**Comment by Regalis11** [comment] 2023-07-21 07:33
Not sure if this is actually a bug or intentional (@itchyOwl ?). To me it'd make sense that if the spineling is in a lucky enough position to be able to fire multiple spikes in rapid succession, it'd do so. And the amount of damage from a spike isn't so high that this'd lead to an unfair instakill.

**Comment by ubertpendragon** [comment] 2023-07-21 07:43
My take was that there's no particular reason for a single spineling to have a 0.3 second cooldown on this attack and this felt like an edge case of taking a lot of damage from a single swarmer-type enemy

**Comment by mygamingaccount** [comment] 2023-07-21 09:01
When you get sloppy and overconfident, exit the ship without cover or backup, your reward is to be bled dry.
_Hey bro! What SONAR watch doing?_

**Comment by VaelophisNyx** [comment] 2023-07-22 04:59
I'd like to counter that while you should be punished for just...sitting there in front of a spineling, it _looks_ incredibly dumb that they can just rapid-fire the spines at you

**Comment by itchyOwl** [comment] 2023-07-31 16:10
It's intentional: they should be able to shoot multiple spikes rapidly. But note that there's a 5 second cooldown for the spikes to grow and to be able to shoot again. If you think it's not balanced well enough, that's a fair feedback. There's certainly room for adjusting it. Got any suggestions for the values? Anyway, it's not a bug.

**Comment by ubertpendragon** [comment] 2023-07-31 16:59
With such numbers, the 5 second cooldown doesnt really matter, since the spineling can shoot all 12 spikes in just short of 4 seconds.

Not that they ever shoot all spikes in quick succession but 5s CD does nothing to stop it

**Comment by itchyOwl** [comment] 2023-10-11 08:20
Could test increasing the secondary cooldown a bit. Moving to backlog.

**Comment by itchyOwl** [comment] 2024-02-15 12:17
Adjusted the secondary cooldown from 0.3 to 0.5 in 9b38718. Increasing it all the way to 1.0 changes the behavior a bit too much when spinelings attack submarines, because they can't shoot the spikes as rapidly anymore. Like I said before, rapid firing is intentional, but not that much when the target is a character.

**Comment by Jasontti** [comment] 2024-03-05 09:49
Tested PR: https://github.com/FakeFishGames/Barotrauma-development/pull/4930
Closing as complete

**Closed by Jasontti** 2024-03-05 09:49 UTC
Labels: Design
